<a href="https://colab.research.google.com/github/hamedesmaeeli/Python_For_Data_Science/blob/main/Copy_of_Kmean_bus_boarding_loacation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

buses = pd.read_csv('bus_kMean_ready.csv')
print ("converted form csv:")
print (buses)

FileNotFoundError: ignored

In [7]:
#Kmean Algorithms
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
#df= np.array([[1,3],[3,3],[4,3],[5,3],[1,2],[4,2],[1,1],[2,1]])
buses_numpy = buses.to_numpy()
buses_numpy[0]

print('buses_numpy: \n',buses_numpy)
kmeans = KMeans(n_clusters=24).fit(buses_numpy)

print(kmeans.labels_)

for i in range(len(buses_numpy)):
    print(buses_numpy[i][0],buses_numpy[i][1],kmeans.labels_[i])

colors = np.array(['r','b','g','y','k','c','m','tomato','cyan','teal'])


#plt.scatter(X[:,0],X[:,1] , color = colors[kmeans.labels_])

NameError: ignored

In [ ]:
import pandas as pd
t0= buses_numpy[0][1]
ts=buses_numpy[len(buses_numpy)-1][1]
print(len(buses_numpy))
print('t0 =',t0)
print('ts =',ts)
time_interval = 600 #second
interval_counts=round((ts-t0)/time_interval)
print('time_intervals',round((ts-t0)/time_interval))
counter=1
buses_counter=1
sum_count=0
interval_numpy = np.ones((interval_counts,2))

for i in range(len(interval_numpy)):
    while buses_numpy[buses_counter][1]<(t0):
        sum_count= sum_count+1
        print(buses_numpy[buses_counter][1],t0)
        print('sum_count=',sum_count)
        buses_counter = buses_counter+1
    interval_numpy[i]=(t0,sum_count)
    t0 = t0+time_interval
    sum_count =0
print(interval_numpy)

df = pd.DataFrame(interval_numpy)
df.to_csv("interval_numpy_10min.csv")

489
t0 = 22557
ts = 79876
time_intervals 96
23138 23157
sum_count= 1
23212 23757
sum_count= 1
23215 23757
sum_count= 2
23260 23757
sum_count= 3
23289 23757
sum_count= 4
23303 23757
sum_count= 5
23491 23757
sum_count= 6
23608 23757
sum_count= 7
23611 23757
sum_count= 8
23714 23757
sum_count= 9
23791 24357
sum_count= 1
23793 24357
sum_count= 2
24120 24357
sum_count= 3
24296 24357
sum_count= 4
24298 24357
sum_count= 5
24669 24957
sum_count= 1
24862 24957
sum_count= 2
25010 25557
sum_count= 1
25187 25557
sum_count= 2
26255 26757
sum_count= 1
26672 26757
sum_count= 2
26856 27357
sum_count= 1
27163 27357
sum_count= 2
27260 27357
sum_count= 3
27314 27357
sum_count= 4
27364 27957
sum_count= 1
27367 27957
sum_count= 2
27437 27957
sum_count= 3
27441 27957
sum_count= 4
27524 27957
sum_count= 5
27583 27957
sum_count= 6
27658 27957
sum_count= 7
27661 27957
sum_count= 8
27759 27957
sum_count= 9
27804 27957
sum_count= 10
27805 27957
sum_count= 11
27810 27957
sum_count= 12
27964 28557
sum_count= 1
28216 28557
sum_count= 2
28302 28557
sum_count= 3
28304 28557
sum_count= 4
28305 28557
sum_count= 5
28310 28557
sum_count= 6
28312 28557
sum_count= 7
28313 28557
sum_count= 8
28315 28557
sum_count= 9
28319 28557
sum_count= 10
28319 28557
sum_count= 11
28411 28557
sum_count= 12
28413 28557
sum_count= 13
28474 28557
sum_count= 14
28541 28557
sum_count= 15
28609 29157
sum_count= 1
28613 29157
sum_count= 2
28662 29157
sum_count= 3
28759 29157
sum_count= 4
28823 29157
sum_count= 5
28827 29157
sum_count= 6
29074 29157
sum_count= 7
29406 29757
sum_count= 1
29493 29757
sum_count= 2
29509 29757
sum_count= 3
30893 30957
sum_count= 1
30937 30957
sum_count= 2
31014 31557
sum_count= 1
31079 31557
sum_count= 2
31115 31557
sum_count= 3
31130 31557
sum_count= 4
31150 31557
sum_count= 5
31174 31557
sum_count= 6
31237 31557
sum_count= 7
31307 31557
sum_count= 8
31446 31557
sum_count= 9
31514 31557
sum_count= 10
31586 32157
sum_count= 1
31590 32157
sum_count= 2
31600 32157
sum_count= 3
31601 32157
sum_count= 4
31605 32157
sum_count= 5
31606 32157
sum_count= 6
31738 32157
sum_count= 7
31888 32157
sum_count= 8
31892 32157
sum_count= 9
32021 32157
sum_count= 10
32093 32157
sum_count= 11
32098 32157
sum_count= 12
32100 32157
sum_count= 13
32103 32157
sum_count= 14
32117 32157
sum_count= 15
32155 32157
sum_count= 16
32239 32757
sum_count= 1
32326 32757
sum_count= 2
32474 32757
sum_count= 3
32626 32757
sum_count= 4
32629 32757
sum_count= 5
32637 32757
sum_count= 6
32654 32757
sum_count= 7
32661 32757
sum_count= 8
32672 32757
sum_count= 9
32692 32757
sum_count= 10
32894 33357
sum_count= 1
33045 33357
sum_count= 2
33485 33957
sum_count= 1
33491 33957
sum_count= 2
33570 33957
sum_count= 3
33572 33957
sum_count= 4
34124 34557
sum_count= 1
34225 34557
sum_count= 2
34375 34557
sum_count= 3
34379 34557
sum_count= 4
34442 34557
sum_count= 5
34555 34557
sum_count= 6
36281 36357
sum_count= 1
36464 36957
sum_count= 1
36470 36957
sum_count= 2
36474 36957
sum_count= 3
36745 36957
sum_count= 4
36945 36957
sum_count= 5
36946 36957
sum_count= 6
37037 37557
sum_count= 1
37087 37557
sum_count= 2
37087 37557
sum_count= 3
37220 37557
sum_count= 4
37222 37557
sum_count= 5
37300 37557
sum_count= 6
37449 37557
sum_count= 7
37451 37557
sum_count= 8
37567 38157
sum_count= 1
37570 38157
sum_count= 2
37723 38157
sum_count= 3
37784 38157
sum_count= 4
37976 38157
sum_count= 5
37980 38157
sum_count= 6
37993 38157
sum_count= 7
38349 38757
sum_count= 1
38351 38757
sum_count= 2
38460 38757
sum_count= 3
38463 38757
sum_count= 4
38599 38757
sum_count= 5
38683 38757
sum_count= 6
38878 39357
sum_count= 1
38998 39357
sum_count= 2
39000 39357
sum_count= 3
39003 39357
sum_count= 4
39004 39357
sum_count= 5
39006 39357
sum_count= 6
39008 39357
sum_count= 7
39181 39357
sum_count= 8
39434 39957
sum_count= 1
39440 39957
sum_count= 2
39456 39957
sum_count= 3
39543 39957
sum_count= 4
39550 39957
sum_count= 5
39678 39957
sum_count= 6
39725 39957
sum_count= 7
39740 39957
sum_count= 8
41102 41157
sum_count= 1
41108 41157
sum_count= 2
41110 41157
sum_count= 3
41155 41157
sum_count= 4
41168 41757
sum_count= 1
41203 41757
sum_count= 2
41250 41757
sum_count= 3
41253 41757
sum_count= 4
41254 41757
sum_count= 5
41257 41757
sum_count= 6
41415 41757
sum_count= 7
41752 41757
sum_count= 8
41756 41757
sum_count= 9
41757 42357
sum_count= 1
41761 42357
sum_count= 2
41765 42357
sum_count= 3
41769 42357
sum_count= 4
41775 42357
sum_count= 5
41780 42357
sum_count= 6
41783 42357
sum_count= 7
41786 42357
sum_count= 8
41787 42357
sum_count= 9
41789 42357
sum_count= 10
42059 42357
sum_count= 11
42060 42357
sum_count= 12
42063 42357
sum_count= 13
42066 42357
sum_count= 14
42067 42357
sum_count= 15
42068 42357
sum_count= 16
42070 42357
sum_count= 17
42143 42357
sum_count= 18
42145 42357
sum_count= 19
42236 42357
sum_count= 20
42503 42957
sum_count= 1
42776 42957
sum_count= 2
42779 42957
sum_count= 3
42843 42957
sum_count= 4
43063 43557
sum_count= 1
43076 43557
sum_count= 2
43163 43557
sum_count= 3
43275 43557
sum_count= 4
43277 43557
sum_count= 5
43338 43557
sum_count= 6
43340 43557
sum_count= 7
43505 43557
sum_count= 8
43510 43557
sum_count= 9
43662 44157
sum_count= 1
43743 44157
sum_count= 2
43749 44157
sum_count= 3
43829 44157
sum_count= 4
43833 44157
sum_count= 5
44466 44757
sum_count= 1
44607 44757
sum_count= 2
44608 44757
sum_count= 3
44613 44757
sum_count= 4
46315 46557
sum_count= 1
46340 46557
sum_count= 2
46419 46557
sum_count= 3
46459 46557
sum_count= 4
46465 46557
sum_count= 5
46521 46557
sum_count= 6
46642 47157
sum_count= 1
46668 47157
sum_count= 2
46691 47157
sum_count= 3
46693 47157
sum_count= 4
46759 47157
sum_count= 5
46767 47157
sum_count= 6
46769 47157
sum_count= 7
46777 47157
sum_count= 8
46781 47157
sum_count= 9
47249 47757
sum_count= 1
47345 47757
sum_count= 2
47463 47757
sum_count= 3
47472 47757
sum_count= 4
47527 47757
sum_count= 5
47542 47757
sum_count= 6
47655 47757
sum_count= 7
47791 48357
sum_count= 1
47792 48357
sum_count= 2
47794 48357
sum_count= 3
47808 48357
sum_count= 4
47921 48357
sum_count= 5
47924 48357
sum_count= 6
48000 48357
sum_count= 7
48001 48357
sum_count= 8
48181 48357
sum_count= 9
48267 48357
sum_count= 10
48535 48957
sum_count= 1
48538 48957
sum_count= 2
48538 48957
sum_count= 3
48539 48957
sum_count= 4
48540 48957
sum_count= 5
48542 48957
sum_count= 6
48542 48957
sum_count= 7
48543 48957
sum_count= 8
48545 48957
sum_count= 9
48547 48957
sum_count= 10
48553 48957
sum_count= 11
48554 48957
sum_count= 12
48773 48957
sum_count= 13
48790 48957
sum_count= 14
48852 48957
sum_count= 15
48885 48957
sum_count= 16
49003 49557
sum_count= 1
49093 49557
sum_count= 2
49101 49557
sum_count= 3
49104 49557
sum_count= 4
49205 49557
sum_count= 5
49268 49557
sum_count= 6
49284 49557
sum_count= 7
49393 49557
sum_count= 8
49404 49557
sum_count= 9
49720 50157
sum_count= 1
51184 51357
sum_count= 1
51185 51357
sum_count= 2
51396 51957
sum_count= 1
51777 51957
sum_count= 2
52017 52557
sum_count= 1
52082 52557
sum_count= 2
52083 52557
sum_count= 3
52089 52557
sum_count= 4
52093 52557
sum_count= 5
52095 52557
sum_count= 6
52096 52557
sum_count= 7
52102 52557
sum_count= 8
52112 52557
sum_count= 9
52162 52557
sum_count= 10
52362 52557
sum_count= 11
52363 52557
sum_count= 12
52367 52557
sum_count= 13
52436 52557
sum_count= 14
52547 52557
sum_count= 15
52549 52557
sum_count= 16
52711 53157
sum_count= 1
53186 53757
sum_count= 1
53394 53757
sum_count= 2
53396 53757
sum_count= 3
53399 53757
sum_count= 4
53528 53757
sum_count= 5
53538 53757
sum_count= 6
53663 53757
sum_count= 7
53727 53757
sum_count= 8
53889 54357
sum_count= 1
53965 54357
sum_count= 2
54057 54357
sum_count= 3
54066 54357
sum_count= 4
54075 54357
sum_count= 5
54133 54357
sum_count= 6
54232 54357
sum_count= 7
54282 54357
sum_count= 8
54445 54957
sum_count= 1
54649 54957
sum_count= 2
54757 54957
sum_count= 3
54882 54957
sum_count= 4
55222 55557
sum_count= 1
55254 55557
sum_count= 2
55571 56157
sum_count= 1
55600 56157
sum_count= 2
55670 56157
sum_count= 3
55805 56157
sum_count= 4
55890 56157
sum_count= 5
55953 56157
sum_count= 6
56107 56157
sum_count= 7
56256 56757
sum_count= 1
56257 56757
sum_count= 2
56391 56757
sum_count= 3
56436 56757
sum_count= 4
56470 56757
sum_count= 5
56473 56757
sum_count= 6
56484 56757
sum_count= 7
56506 56757
sum_count= 8
56511 56757
sum_count= 9
56563 56757
sum_count= 10
56631 56757
sum_count= 11
56632 56757
sum_count= 12
56634 56757
sum_count= 13
56635 56757
sum_count= 14
56637 56757
sum_count= 15
56638 56757
sum_count= 16
56696 56757
sum_count= 17
56756 56757
sum_count= 18
56811 57357
sum_count= 1
56963 57357
sum_count= 2
56965 57357
sum_count= 3
56968 57357
sum_count= 4
56969 57357
sum_count= 5
56971 57357
sum_count= 6
57071 57357
sum_count= 7
57278 57357
sum_count= 8
57281 57357
sum_count= 9
57460 57957
sum_count= 1
57522 57957
sum_count= 2
57524 57957
sum_count= 3
59209 59757
sum_count= 1
59804 60357
sum_count= 1
59822 60357
sum_count= 2
59950 60357
sum_count= 3
60372 60957
sum_count= 1
60374 60957
sum_count= 2
60377 60957
sum_count= 3
60378 60957
sum_count= 4
60381 60957
sum_count= 5
60388 60957
sum_count= 6
60438 60957
sum_count= 7
60440 60957
sum_count= 8
60625 60957
sum_count= 9
60626 60957
sum_count= 10
60685 60957
sum_count= 11
60817 60957
sum_count= 12
60818 60957
sum_count= 13
60837 60957
sum_count= 14
60947 60957
sum_count= 15
61032 61557
sum_count= 1
61035 61557
sum_count= 2
61036 61557
sum_count= 3
61044 61557
sum_count= 4
61045 61557
sum_count= 5
61385 61557
sum_count= 6
61387 61557
sum_count= 7
61389 61557
sum_count= 8
61390 61557
sum_count= 9
61391 61557
sum_count= 10
61394 61557
sum_count= 11
61395 61557
sum_count= 12
61397 61557
sum_count= 13
61397 61557
sum_count= 14
61398 61557
sum_count= 15
61399 61557
sum_count= 16
61400 61557
sum_count= 17
61403 61557
sum_count= 18
61472 61557
sum_count= 19
61474 61557
sum_count= 20
61532 61557
sum_count= 21
61535 61557
sum_count= 22
61551 61557
sum_count= 23
61604 62157
sum_count= 1
61678 62157
sum_count= 2
61929 62157
sum_count= 3
61934 62157
sum_count= 4
62313 62757
sum_count= 1
62565 62757
sum_count= 2
62581 62757
sum_count= 3
62655 62757
sum_count= 4
62731 62757
sum_count= 5
62840 63357
sum_count= 1
62843 63357
sum_count= 2
62846 63357
sum_count= 3
62850 63357
sum_count= 4
62851 63357
sum_count= 5
63114 63357
sum_count= 6
63116 63357
sum_count= 7
63123 63357
sum_count= 8
63160 63357
sum_count= 9
63913 63957
sum_count= 1
63930 63957
sum_count= 2
64065 64557
sum_count= 1
64145 64557
sum_count= 2
64233 64557
sum_count= 3
64269 64557
sum_count= 4
64812 65157
sum_count= 1
64960 65157
sum_count= 2
65018 65157
sum_count= 3
65098 65157
sum_count= 4
65131 65157
sum_count= 5
65133 65157
sum_count= 6
65137 65157
sum_count= 7
65276 65757
sum_count= 1
65276 65757
sum_count= 2
65277 65757
sum_count= 3
65303 65757
sum_count= 4
65482 65757
sum_count= 5
65896 66357
sum_count= 1
65898 66357
sum_count= 2
65994 66357
sum_count= 3
66087 66357
sum_count= 4
66087 66357
sum_count= 5
66089 66357
sum_count= 6
66093 66357
sum_count= 7
66095 66357
sum_count= 8
66098 66357
sum_count= 9
66100 66357
sum_count= 10
66107 66357
sum_count= 11
66128 66357
sum_count= 12
66141 66357
sum_count= 13
66200 66357
sum_count= 14
66367 66957
sum_count= 1
66368 66957
sum_count= 2
66450 66957
sum_count= 3
66568 66957
sum_count= 4
66572 66957
sum_count= 5
66573 66957
sum_count= 6
66578 66957
sum_count= 7
66662 66957
sum_count= 8
66853 66957
sum_count= 9
67219 67557
sum_count= 1
67220 67557
sum_count= 2
70251 70557
sum_count= 1
70253 70557
sum_count= 2
70255 70557
sum_count= 3
70321 70557
sum_count= 4
70322 70557
sum_count= 5
70323 70557
sum_count= 6
70325 70557
sum_count= 7
70328 70557
sum_count= 8
70331 70557
sum_count= 9
70334 70557
sum_count= 10
70336 70557
sum_count= 11
70339 70557
sum_count= 12
70342 70557
sum_count= 13
70346 70557
sum_count= 14
70581 71157
sum_count= 1
70678 71157
sum_count= 2
70680 71157
sum_count= 3
70691 71157
sum_count= 4
70755 71157
sum_count= 5
70857 71157
sum_count= 6
70992 71157
sum_count= 7
71495 71757
sum_count= 1
71499 71757
sum_count= 2
71646 71757
sum_count= 3
71913 72357
sum_count= 1
71914 72357
sum_count= 2
72175 72357
sum_count= 3
76369 76557
sum_count= 1
76884 77157
sum_count= 1
77053 77157
sum_count= 2
77355 77757
sum_count= 1
78081 78357
sum_count= 1
78824 78957
sum_count= 1
78834 78957
sum_count= 2
79405 79557
sum_count= 1
[[2.2557e+04 0.0000e+00]
 [2.3157e+04 1.0000e+00]
 [2.3757e+04 9.0000e+00]
 [2.4357e+04 5.0000e+00]
 [2.4957e+04 2.0000e+00]
 [2.5557e+04 2.0000e+00]
 [2.6157e+04 0.0000e+00]
 [2.6757e+04 2.0000e+00]
 [2.7357e+04 4.0000e+00]
 [2.7957e+04 1.2000e+01]
 [2.8557e+04 1.5000e+01]
 [2.9157e+04 7.0000e+00]
 [2.9757e+04 3.0000e+00]
 [3.0357e+04 0.0000e+00]
 [3.0957e+04 2.0000e+00]
 [3.1557e+04 1.0000e+01]
 [3.2157e+04 1.6000e+01]
 [3.2757e+04 1.0000e+01]
 [3.3357e+04 2.0000e+00]
 [3.3957e+04 4.0000e+00]
 [3.4557e+04 6.0000e+00]
 [3.5157e+04 0.0000e+00]
 [3.5757e+04 0.0000e+00]
 [3.6357e+04 1.0000e+00]
 [3.6957e+04 6.0000e+00]
 [3.7557e+04 8.0000e+00]
 [3.8157e+04 7.0000e+00]
 [3.8757e+04 6.0000e+00]
 [3.9357e+04 8.0000e+00]
 [3.9957e+04 8.0000e+00]
 [4.0557e+04 0.0000e+00]
 [4.1157e+04 4.0000e+00]
 [4.1757e+04 9.0000e+00]
 [4.2357e+04 2.0000e+01]
 [4.2957e+04 4.0000e+00]
 [4.3557e+04 9.0000e+00]
 [4.4157e+04 5.0000e+00]
 [4.4757e+04 4.0000e+00]
 [4.5357e+04 0.0000e+00]
 [4.5957e+04 0.0000e+00]
 [4.6557e+04 6.0000e+00]
 [4.7157e+04 9.0000e+00]
 [4.7757e+04 7.0000e+00]
 [4.8357e+04 1.0000e+01]
 [4.8957e+04 1.6000e+01]
 [4.9557e+04 9.0000e+00]
 [5.0157e+04 1.0000e+00]
 [5.0757e+04 0.0000e+00]
 [5.1357e+04 2.0000e+00]
 [5.1957e+04 2.0000e+00]
 [5.2557e+04 1.6000e+01]
 [5.3157e+04 1.0000e+00]
 [5.3757e+04 8.0000e+00]
 [5.4357e+04 8.0000e+00]
 [5.4957e+04 4.0000e+00]
 [5.5557e+04 2.0000e+00]
 [5.6157e+04 7.0000e+00]
 [5.6757e+04 1.8000e+01]
 [5.7357e+04 9.0000e+00]
 [5.7957e+04 3.0000e+00]
 [5.8557e+04 0.0000e+00]
 [5.9157e+04 0.0000e+00]
 [5.9757e+04 1.0000e+00]
 [6.0357e+04 3.0000e+00]
 [6.0957e+04 1.5000e+01]
 [6.1557e+04 2.3000e+01]
 [6.2157e+04 4.0000e+00]
 [6.2757e+04 5.0000e+00]
 [6.3357e+04 9.0000e+00]
 [6.3957e+04 2.0000e+00]
 [6.4557e+04 4.0000e+00]
 [6.5157e+04 7.0000e+00]
 [6.5757e+04 5.0000e+00]
 [6.6357e+04 1.4000e+01]
 [6.6957e+04 9.0000e+00]
 [6.7557e+04 2.0000e+00]
 [6.8157e+04 0.0000e+00]
 [6.8757e+04 0.0000e+00]
 [6.9357e+04 0.0000e+00]
 [6.9957e+04 0.0000e+00]
 [7.0557e+04 1.4000e+01]
 [7.1157e+04 7.0000e+00]
 [7.1757e+04 3.0000e+00]
 [7.2357e+04 3.0000e+00]
 [7.2957e+04 0.0000e+00]
 [7.3557e+04 0.0000e+00]
 [7.4157e+04 0.0000e+00]
 [7.4757e+04 0.0000e+00]
 [7.5357e+04 0.0000e+00]
 [7.5957e+04 0.0000e+00]
 [7.6557e+04 1.0000e+00]
 [7.7157e+04 2.0000e+00]
 [7.7757e+04 1.0000e+00]
 [7.8357e+04 1.0000e+00]
 [7.8957e+04 2.0000e+00]
 [7.9557e+04 1.0000e+00]]

In [ ]:
df_bus_service = pd.DataFrame(columns=["index","time_in","time_out"])
bus_services =np.array([])
bus_service_counter=0;
zero_count=0
for i in range(len(interval_numpy)):
    if interval_numpy[i][1]==0:
        if zero_count>0 :
            out_time = interval_numpy[i][0]+time_interval

        else:
          #  print(interval_numpy[i][1])
          # print(interval_numpy[i][0])
            bus_service_counter=bus_service_counter+1
            in_time=interval_numpy[i][0]
            out_time=interval_numpy[i][0]+time_interval
            bus_services_row =[bus_service_counter,in_time,out_time]
          #  df_bus_service.add([bus_service_counter,in_time,out_time])
            df_bus_service.loc[len(df_bus_service)] = bus_services_row
            zero_count = zero_count+1
    else:
        zero_count=0
print(df_bus_service)
df_bus_service.to_csv("bus_services.csv")

station_Counter=0
buses_with_station = pd.DataFrame(columns=["TID","Time","StationID","Is_OD"])
print(buses_with_station)
bus_counter=0;
for i in range(len(df_bus_service)):     #Orgin_destination Staions
    time_in_od = df_bus_service.loc[i][1] #start_in orgin or destination
    time_out_od = df_bus_service.loc[i][2]#end_out orgin or destination
    #print(time_in_od,time_out_od)
    station_Counter = station_Counter+1
    for j in range(len(buses_numpy)):
        #print(buses_numpy[j][1])
        #buses_numpy[i][1]<=(time_in_od) and [bus_counter][1]>(time_out_od)
        #print('added',buses_numpy[bus_counter][1])
        #bus_station_row = [buses_numpy[bus_counter][0],buses_numpy[bus_counter][1],station_Counter,'yes']

        if(buses_numpy[j][1]>=(time_in_od) and buses_numpy[j][1]<=(time_out_od)):
            #print([buses_numpy[j][0],buses_numpy[j][1],station_Counter,'yes'])
            buses_with_station.loc[len(buses_with_station)]=[buses_numpy[j][0],buses_numpy[j][1],station_Counter,'yes']
##dd
for i in range(len(df_bus_service)-1):     #Other Staions

    time_start = df_bus_service.loc[i][2]#end_out orgin or destination
    time_stop = df_bus_service.loc[i+1][1] #start_in orgin or destination
    print('time_start','time_stop',time_start,time_stop)
    station_Counter = station_Counter+1
    df_bus_partial = pd.DataFrame(columns=["TID","Time"])

    for j in range(len(buses_numpy)):
        #print(buses_numpy[j][1])
        #buses_numpy[i][1]<=(time_in_od) and [bus_counter][1]>(time_out_od)
        #print('added',buses_numpy[bus_counter][1])
        #bus_station_row = [buses_numpy[bus_counter][0],buses_numpy[bus_counter][1],station_Counter,'yes']

        if(buses_numpy[j][1]>(time_start) and buses_numpy[j][1]<(time_stop)):
            #print([buses_numpy[j][0],buses_numpy[j][1],station_Counter,'no'])
            df_bus_partial.loc[len(df_bus_partial)]=[buses_numpy[j][0],buses_numpy[j][1]]
           # buses_with_station.loc[len(buses_with_station)]=[buses_numpy[j][0],buses_numpy[j][1],station_Counter,'yes']
    print(df_bus_partial)
    df_bus_partial.to_csv("bus_partial"+str(i)+".csv")

    kmeans = KMeans(n_clusters=10).fit(df_bus_partial.to_numpy())

    print(kmeans.labels_)

buses_with_station.to_csv("bus_with_station.csv")

   index  time_in  time_out
0    1.0  22557.0   23157.0
1    2.0  26157.0   26757.0
2    3.0  30357.0   30957.0
3    4.0  35157.0   35757.0
4    5.0  40557.0   41157.0
5    6.0  45357.0   45957.0
6    7.0  50757.0   51357.0
7    8.0  58557.0   59157.0
8    9.0  68157.0   68757.0
9   10.0  72957.0   73557.0
Empty DataFrame
Columns: [TID, Time, StationID, Is_OD]
Index: []
time_start time_stop 23157.0 26157.0
   TID   Time
0    3  23212
1    4  23215
2    5  23260
3    6  23289
4    7  23303
5    8  23491
6    9  23608
7   10  23611
8   11  23714
9   12  23791
10  13  23793
11  14  24120
12  15  24296
13  16  24298
14  17  24669
15  18  24862
16  19  25010
17  20  25187
[2 2 2 2 2 9 0 0 5 5 5 6 3 3 1 8 4 7]
time_start time_stop 26757.0 30357.0
   TID   Time
0   23  26856
1   24  27163
2   25  27260
3   26  27314
4   27  27364
5   28  27367
6   29  27437
7   30  27441
8   31  27524
9   32  27583
10  33  27658
11  34  27661
12  35  27759
13  36  27804
14  37  27805
15  38  27810
16  39  27964
17  40  28216
18  41  28302
19  42  28304
20  43  28305
21  44  28310
22  45  28312
23  46  28313
24  47  28315
25  48  28319
26  49  28319
27  50  28411
28  51  28413
29  52  28474
30  53  28541
31  54  28609
32  55  28613
33  56  28662
34  57  28759
35  58  28823
36  59  28827
37  60  29074
38  61  29406
39  62  29493
40  63  29509
[6 3 3 7 7 7 7 7 9 9 9 9 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 8 8 8
 4 2 2 2]
time_start time_stop 30957.0 35157.0
    TID   Time
0    66  31014
1    67  31079
2    68  31115
3    69  31130
4    70  31150
5    71  31174
6    72  31237
7    73  31307
8    74  31446
9    75  31514
10   76  31586
11   77  31590
12   78  31600
13   79  31601
14   80  31605
15   81  31606
16   82  31738
17   83  31888
18   84  31892
19   85  32021
20   86  32093
21   87  32098
22   88  32100
23   89  32103
24   90  32117
25   91  32155
26   92  32239
27   93  32326
28   94  32474
29   95  32626
30   96  32629
31   97  32637
32   98  32654
33   99  32661
34  100  32672
35  101  32692
36  102  32894
37  103  33045
38  104  33485
39  105  33491
40  106  33570
41  107  33572
42  108  34124
43  109  34225
44  110  34375
45  111  34379
46  112  34442
47  113  34555
[5 5 5 5 5 5 5 5 2 2 2 2 2 2 2 2 2 7 7 0 0 0 0 0 0 0 9 9 9 3 3 3 3 3 3 3 8
 8 4 4 4 4 6 6 1 1 1 1]
time_start time_stop 35757.0 40557.0
    TID   Time
0   114  36281
1   115  36464
2   116  36470
3   117  36474
4   118  36745
5   119  36945
6   120  36946
7   121  37037
8   122  37087
9   123  37087
10  124  37220
11  125  37222
12  126  37300
13  127  37449
14  128  37451
15  129  37567
16  130  37570
17  131  37723
18  132  37784
19  133  37976
20  134  37980
21  135  37993
22  136  38349
23  137  38351
24  138  38460
25  139  38463
26  140  38599
27  141  38683
28  142  38878
29  143  38998
30  144  39000
31  145  39003
32  146  39004
33  147  39006
34  148  39008
35  149  39181
36  150  39434
37  151  39440
38  152  39456
39  153  39543
40  154  39550
41  155  39678
42  156  39725
43  157  39740
[5 5 5 5 0 0 0 0 8 8 8 8 8 4 4 4 4 4 6 6 6 6 2 2 2 2 9 9 1 1 1 1 1 1 1 1 7
 7 7 7 7 3 3 3]
time_start time_stop 41157.0 45357.0
    TID   Time
0   162  41168
1   163  41203
2   164  41250
3   165  41253
4   166  41254
5   167  41257
6   168  41415
7   169  41752
8   170  41756
9   171  41757
10  172  41761
11  173  41765
12  174  41769
13  175  41775
14  176  41780
15  177  41783
16  178  41786
17  179  41787
18  180  41789
19  181  42059
20  182  42060
21  183  42063
22  184  42066
23  185  42067
24  186  42068
25  187  42070
26  188  42143
27  189  42145
28  190  42236
29  191  42503
30  192  42776
31  193  42779
32  194  42843
33  195  43063
34  196  43076
35  197  43163
36  198  43275
37  199  43277
38  200  43338
39  201  43340
40  202  43505
41  203  43510
42  204  43662
43  205  43743
44  206  43749
45  207  43829
46  208  43833
47  209  44466
48  210  44607
49  211  44608
50  212  44613
[3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 4 9 6 6 6 8 8 8 2
 2 2 2 7 7 5 5 5 5 5 0 0 0 0]
time_start time_stop 45957.0 50757.0
    TID   Time
0   213  46315
1   214  46340
2   215  46419
3   216  46459
4   217  46465
5   218  46521
6   219  46642
7   220  46668
8   221  46691
9   222  46693
10  223  46759
11  224  46767
12  225  46769
13  226  46777
14  227  46781
15  228  47249
16  229  47345
17  230  47463
18  231  47472
19  232  47527
20  233  47542
21  234  47655
22  235  47791
23  236  47792
24  237  47794
25  238  47808
26  239  47921
27  240  47924
28  241  48000
29  242  48001
30  243  48181
31  244  48267
32  245  48535
33  246  48538
34  247  48538
35  248  48539
36  249  48540
37  250  48542
38  251  48542
39  252  48543
40  253  48545
41  254  48547
42  255  48553
43  256  48554
44  257  48773
45  258  48790
46  259  48852
47  260  48885
48  261  49003
49  262  49093
50  263  49101
51  264  49104
52  265  49205
53  266  49268
54  267  49284
55  268  49393
56  269  49404
57  270  49720
[0 0 0 0 0 0 4 4 4 4 4 4 4 4 4 6 6 6 6 6 6 2 2 2 2 2 2 2 3 3 3 3 8 8 8 8 8
 8 8 8 8 8 8 8 5 5 5 5 1 1 1 1 1 7 7 7 7 9]
time_start time_stop 51357.0 58557.0
    TID   Time
0   273  51396
1   274  51777
2   275  52017
3   276  52082
4   277  52083
..  ...    ...
73  346  57278
74  347  57281
75  348  57460
76  349  57522
77  350  57524

[78 rows x 2 columns]
[6 8 8 8 8 8 8 8 8 8 8 8 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 2 2 2 2 2 2 2 2 2 7
 7 7 7 7 3 3 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 0 0 0 0 0 0 0 0 9
 9 9 9 9]
time_start time_stop 59157.0 68157.0
     TID   Time
0    351  59209
1    352  59804
2    353  59822
3    354  59950
4    355  60372
..   ...    ...
98   449  66578
99   450  66662
100  451  66853
101  452  67219
102  453  67220

[103 rows x 2 columns]
[5 5 5 5 1 1 1 1 1 1 1 1 1 1 1 8 8 8 8 8 8 8 8 8 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 7 7 7 7 7 7 4 4 4 4 4 4 4 4
 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 6 6 6 9 9 9]
time_start time_stop 68757.0 72957.0
    TID   Time
0   454  70251
1   455  70253
2   456  70255
3   457  70321
4   458  70322
5   459  70323
6   460  70325
7   461  70328
8   462  70331
9   463  70334
10  464  70336
11  465  70339
12  466  70342
13  467  70346
14  468  70581
15  469  70678
16  470  70680
17  471  70691
18  472  70755
19  473  70857
20  474  70992
21  475  71495
22  476  71499
23  477  71646
24  478  71913
25  479  71914
26  480  72175
[8 8 8 0 0 0 0 0 0 0 0 0 0 0 9 2 2 2 2 4 6 3 3 7 1 1 5]

In [ ]:
import pandas as pd

routes = pd.read_csv('routes.csv')
print ("converted form csv:")
print (routes)
line_num ='8'
print('stations in a specefic bus line')
filter_go_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='go')]
filter_back_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='back')]
filter_go_back_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='go_back')]
print ('len-of-go stations:',len(filter_go_stations))
print ('len-of-back stations:',len(filter_back_stations))
print ('len-of-back stations:',len(filter_go_back_stations))

converted form csv:
      station_code  line order go_back                   station_name  \
0             3169     1     1      go                    ????-157-57
1             3170     1     2      go                ???? ???? ?????
2             3172     1     3      go                          ?????
3             3175     1     4      go                     ??? ??????
4             3177     1     5      go                          ?????
...            ...   ...   ...     ...                            ...
5023          2898  brt3    28    back                         ??????
5024          2885  brt3    29    back                ????? ???? ????
5025          2886  brt3    30    back                      ???? ????
5026          3931  brt3    31    back                          ?????
5027          2870  brt3    32    back  ?????? ????? ????????-????? 3

      geo_width  geo_length station_type roate_type in_terminal
0     51.731912   32.720558           od     normal          no
1     51.728978   32.715887       normal     normal          no
2     51.727200   32.712987       normal     normal          no
3     51.725108   32.710537       normal     normal          no
4     51.720581   32.707897       normal     normal          no
...         ...         ...          ...        ...         ...
5023  51.763670   32.654585       normal        BRT          no
5024  51.768907   32.652085       normal        BRT          no
5025  51.774118   32.649536       normal        BRT          no
5026  51.775672   32.648610       normal     normal          no
5027  51.783792   32.645565           od     normal         yes

[5028 rows x 10 columns]
stations in a specefic bus line
len-of-go stations: 27
len-of-back stations: 29
len-of-back stations: 0

In [20]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

bus_transactions = pd.read_csv('bus_transactions980623.csv')
print ("converted form csv:")
print (bus_transactions)

routes = pd.read_csv('routes.csv')


line_num = 1
print('stations in a specefic bus line')
filter_stations = bus_transactions.loc[bus_transactions['LineCode'] == line_num]
print(filter_stations)

l = bus_transactions.LineCode.unique()
print('unique Line Codes: \n ',sorted(l))

print('unique plats: \n ',bus_transactions.plat.unique())

for i in range(len(l)):
   # print('transactions in lines',l[i])
    s = bus_transactions.loc[bus_transactions['LineCode'] == l[i]]


    line_num =str(int(l[i]))
    print('stations in a specefic bus line',line_num)
    filter_go_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='go')]
    filter_back_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='back')]
    filter_go_back_stations = routes.loc[(routes['line'] == line_num) & (routes['go_back'] =='go_back')]
    print ('len-of-go stations:',len(filter_go_stations))
    print ('len-of-back stations:',len(filter_back_stations))
    print ('len-of-go back stations:',len(filter_go_back_stations))

    orig_station = filter_go_stations.to_numpy()[0][0]
    dest_station =  filter_back_stations.to_numpy()[0][0]
    print('first Station ',filter_go_stations.to_numpy()[0],filter_go_stations.to_numpy()[0][0])
    print('last Station ',filter_back_stations.to_numpy()[0])

    print(s.plat.unique())
    p = s.plat.unique()

    for j in range(len(p)):
        print('transactions in line',l[i],'plat',p[j])
        ps  = bus_transactions.loc[(bus_transactions['LineCode'] == l[i]) & (bus_transactions['plat'] ==p[j])]
        print(ps)

        # For each buckets of transactions in a specific line and plat, we try to  cluster transaction in related station
        # ps evaluate to buses in my previous code

        buses_numpy = ps.to_numpy()
        print('first row of the selected chunck : \n',buses_numpy[0])

        t0= buses_numpy[0][3]
        ts=buses_numpy[len(buses_numpy)-1][3]
        print(len(buses_numpy))
        print('t0 =',t0)
        print('ts =',ts)
        time_interval = 600 #second for finding orgin or destination stations(over 10 minute)
        interval_counts=round((ts-t0)/time_interval)
        print('time_intervals',round((ts-t0)/time_interval))
        counter=1
        buses_counter=1
        sum_count=0
        interval_numpy = np.ones((interval_counts,2))

        for k in range(len(interval_numpy)):
            while buses_numpy[buses_counter][3]<(t0):
                sum_count= sum_count+1
                #print(buses_numpy[buses_counter][3],t0)
                #print('sum_count=',sum_count)
                buses_counter = buses_counter+1
            interval_numpy[k]=(t0,sum_count)
            t0 = t0+time_interval
            sum_count =0
        print('10min interval view \n for line',l[i],'plat',p[j],' \n',interval_numpy)

        #Calculate 10min intervals to find origin or destinations - Each row means a go or back
        df_bus_service = pd.DataFrame(columns=["time_in","time_out"])
        bus_services =np.array([])
        bus_service_counter=0;
        zero_count=0
        for k in range(len(interval_numpy)):
            if interval_numpy[k][1]==0:
                if zero_count>0 :
                    out_time = interval_numpy[k][0]+time_interval

                else:
                  #  print(interval_numpy[i][1])
                  # print(interval_numpy[i][0])
                    bus_service_counter=bus_service_counter+1
                    in_time=interval_numpy[k][0]
                    out_time=interval_numpy[k][0]+time_interval
                    bus_services_row =[in_time,out_time]
                  #  df_bus_service.add([bus_service_counter,in_time,out_time])
                    df_bus_service.loc[len(df_bus_service)] = bus_services_row
                    zero_count = zero_count+1
            else:
                zero_count=0
        print('Origin destination interval view \n',df_bus_service)

        #Assign origin and destination stations to the transactions
      #  buses_with_station = pd.DataFrame(columns=["TID","Time","StationID","Is_OD"])
        station_Counter = 1
        station_org_or_des = orig_station
        buses_with_station = pd.DataFrame(columns=["CardID","LineCode","FDate","Time","plat","Station"])
        for k in range(len(df_bus_service)):     #Orgin_destination Staions
            time_in_od = df_bus_service.loc[k][0] #start_in orgin or destination
            time_out_od = df_bus_service.loc[k][1]#end_out orgin or destination
            #print('time_in_od,time_out_od:',time_in_od,time_out_od)

            if station_Counter<0:
              station_org_or_des=dest_station
            else:
              station_org_or_des = orig_station

            for m in range(len(buses_numpy)):
                #print(buses_numpy[j][1])
                #buses_numpy[i][1]<=(time_in_od) and [bus_counter][1]>(time_out_od)
                #print('added',buses_numpy[bus_counter][1])
                #bus_station_row = [buses_numpy[bus_counter][0],buses_numpy[bus_counter][1],station_Counter,'yes']

                if(buses_numpy[m][3]>=(time_in_od) and buses_numpy[m][3]<=(time_out_od)):
                    #print([buses_numpy[j][0],buses_numpy[j][1],station_Counter,'yes'])
                    buses_with_station.loc[len(buses_with_station)]=[buses_numpy[m][0],buses_numpy[m][1],buses_numpy[m][2],buses_numpy[m][3],buses_numpy[m][4],station_org_or_des]
            station_Counter= -station_Counter
            #print('station_counter',station_Counter)
        #first attempt to update stations of transactions - only orgin or destination
        print('OD bus stations of transactions: \n',buses_with_station)


        station_Counter = 1

        ##dd
        for k in range(len(df_bus_service)-1):     #Other Staions

            time_start = df_bus_service.loc[k][1]#end_out orgin or destination
            time_stop = df_bus_service.loc[k+1][0] #start_in orgin or destination
            print('time_start','time_stop',time_start,time_stop)
            station_Counter = station_Counter+1
            df_bus_partial = pd.DataFrame(columns=["CardID","LineCode","FDate","Time","plat"])
            for m in range(len(buses_numpy)):
                #print(buses_numpy[j][1])
                #buses_numpy[i][1]<=(time_in_od) and [bus_counter][1]>(time_out_od)
                #print('added',buses_numpy[bus_counter][1])
                #bus_station_row = [buses_numpy[bus_counter][0],buses_numpy[bus_counter][1],station_Counter,'yes']

                if(buses_numpy[m][3]>(time_start) and buses_numpy[m][3]<(time_stop)):
                    #print([buses_numpy[j][0],buses_numpy[j][1],station_Counter,'no'])
                    df_bus_partial.loc[len(df_bus_partial)]=[buses_numpy[m][0],buses_numpy[m][1],buses_numpy[m][2],buses_numpy[m][3],buses_numpy[m][4]]
                   # buses_with_station.loc[len(buses_with_station)]=[buses_numpy[j][0],buses_numpy[j][1],station_Counter,'yes']
            print('df_bus_partial : \n',df_bus_partial)

            partial_times = df_bus_partial[["Time","LineCode"]]
            print(partial_times)


            if station_Counter<0: #Back
              station_org_or_des=dest_station
            else:   #Go
              station_org_or_des = orig_station
              if(len(df_bus_partial) >=len(filter_go_stations)):
                print('if(len(df_bus_partial) >=len(filter_go_stations))')
                kmeans = KMeans(n_clusters=len(filter_go_stations),random_state=0, init='k-means++').fit(partial_times.to_numpy())
                print('kmeans.labels_ in go routes',kmeans.labels_)

                kmeansLabels = pd.DataFrame(kmeans.labels_,columns=["label"])
                print('kmeansLabels \n',kmeansLabels.label.unique())


            #df_bus_partial.to_csv("bus_partial"+str(i)+".csv")

            #kmeans = KMeans(n_clusters=10).fit(df_bus_partial.to_numpy())

            #print(kmeans.labels_)

        #buses_with_station.to_csv("bus_with_station.csv")

converted form csv:
            CardID  LineCode       FDate   Time  plat
0        542446139         1  1398/06/23  24030  A145
1        542446139         1  1398/06/23  24030  A145
2       2620656172         1  1398/06/23  24302  A145
3       2620656172         1  1398/06/23  24302  A145
4       3446252780         1  1398/06/23  26200  A145
...            ...       ...         ...    ...   ...
906075  2115925572       998  1398/06/23  54793   A43
906076  1765378436       998  1398/06/23  56797   A43
906077  1765378436       998  1398/06/23  56797   A43
906078  3997192356       998  1398/06/23  58169   A43
906079  3997192356       998  1398/06/23  58169   A43

[906080 rows x 5 columns]
stations in a specefic bus line
           CardID  LineCode       FDate   Time  plat
0       542446139         1  1398/06/23  24030  A145
1       542446139         1  1398/06/23  24030  A145
2      2620656172         1  1398/06/23  24302  A145
3      2620656172         1  1398/06/23  24302  A145
4      3446252780         1  1398/06/23  26200  A145
...           ...       ...         ...    ...   ...
31141  1407250245         1  1398/06/23  32846   N77
31142  1598737700         1  1398/06/23  32851   N77
31143  1598737700         1  1398/06/23  32851   N77
31144  1407179025         1  1398/06/23  33307   N77
31145  1407179025         1  1398/06/23  33307   N77

[31146 rows x 5 columns]
unique Line Codes:
  [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86, 88, 90, 91, 92, 94, 95, 96, 97, 98, 101, 102, 103, 106, 120, 145, 146, 147, 149, 150, 151, 152, 155, 156, 157, 167, 176, 267, 998, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1010, 1011, 1012, 1013, 1015, 1018, 1019]
unique plats:
  ['A145' 'A148' 'A34' 'B25' 'C16' 'C62' 'C65' 'D23' 'D33' 'D35' 'D44' 'D92'
 'D94' 'E31' 'E52' 'E55' 'F82' 'M50' 'N11' 'N167' 'N54' 'N77' 'A144' 'A17'
 'A31' 'A38' 'D49' 'D52' 'E187' 'F11' 'F118' 'F150' 'F152' 'F153' 'F21'
 'F81' 'M39' 'N190' 'A111' 'A147' 'A68' 'D40' 'D57' 'D65' 'D70' 'E141'
 'E20' 'E27' 'E45' 'M14' 'M142' 'M168' 'M17' 'M203' 'M206' 'A16' 'B72'
 'C30' 'N155' 'A33' 'A42' 'A71' 'C13' 'C31' 'E232' 'F110' 'N57' 'N65'
 'A156' 'B40' 'C34' 'D66' 'E19' 'E208' 'E23' 'F147' 'M61' 'M73' 'E197'
 'F104' 'F72' 'M208' 'E186' 'F55' 'A30' 'A55' 'C18' 'F95' 'A22' 'B27'
 'N152' 'A70' 'A23' 'D45' 'F45' 'A60' 'N195' 'C32' 'D32' 'E201' 'F162'
 'F62' 'F92' 'F99' 'A49' 'B62' 'D31' 'F161' 'F167' 'F168' 'F172' 'F181'
 'F182' 'M12' 'M21' 'M22' 'N143' 'N97' 'F106' 'M34' 'N13' 'N72' 'A37'
 'C27' 'N146' 'D79' 'E206' 'F27' 'M128' 'N115' 'A141' 'B66' 'D28' 'E120'
 'F108' 'F173' 'M121' 'M205' 'M96' 'N71' 'A136' 'M42' 'M46' 'N89' 'E234'
 'M35' 'M59' 'E171' 'M107' 'E211' 'E109' 'E209' 'F16' 'F76' 'M179' 'M27'
 'N34' 'D62' 'E14' 'E194' 'E195' 'E21' 'E239' 'E78' 'E87' 'F13' 'N50'
 'E37' 'F169' 'M148' 'N103' 'B44' 'F129' 'A65' 'B39' 'C17' 'C24' 'D47'
 'E131' 'E132' 'E188' 'E33' 'E92' 'F149' 'F176' 'M45' 'M77' 'N175' 'N182'
 'N82' 'B20' 'D77' 'E117' 'E151' 'F135' 'F175' 'M75' 'M76' 'N125' 'N75'
 'A117' 'A126' 'A129' 'F183' 'F58' 'F74' 'M149' 'M153' 'C55' 'E238' 'A110'
 'E110' 'E236' 'F70' 'F80' 'M116' 'N18' 'A112' 'E243' 'F40' 'F85' 'N58'
 'A166' 'E142' 'E46' 'F130' 'M133' 'M54' 'M56' 'M57' 'M86' 'N100' 'N106'
 'C57' 'D55' 'D95' 'E212' 'E36' 'E39' 'F121' 'F98' 'N199' 'N37' 'A140'
 'A154' 'A158' 'A64' 'B38' 'E169' 'F117' 'F146' 'F174' 'M146' 'M52' 'A27'
 'B69' 'D86' 'E174' 'E240' 'F18' 'F63' 'M152' 'M36' 'N113' 'N157' 'A120'
 'A151' 'A152' 'A160' 'B126' 'C58' 'D13' 'D15' 'D50' 'D72' 'E65' 'M150'
 'M178' 'M202' 'M70' 'N121' 'N20' 'N96' 'A41' 'E106' 'E26' 'F64' 'M18'
 'M91' 'A118' 'B14' 'B73' 'C36' 'C37' 'E228' 'F138' 'F139' 'F145' 'M190'
 'M211' 'N161' 'N169' 'A29' 'B17' 'B55' 'B78' 'C12' 'C49' 'E15' 'E170'
 'E62' 'M134' 'M139' 'M140' 'M209' 'M37' 'M58' 'N162' 'B42' 'M138' 'M97'
 'N107' 'N153' 'B45' 'B48' 'B51' 'B68' 'B74' 'B77' 'C20' 'C64' 'D80'
 'E214' 'F26' 'M41' 'M44' 'E88' 'B64' 'D41' 'F90' 'M101' 'M158' 'A12'
 'A130' 'A48' 'A50' 'A53' 'A59' 'B112' 'B113' 'C40' 'E179' 'F101' 'M104'
 'M105' 'M106' 'M111' 'M113' 'M118' 'M144' 'M159' 'M169' 'M170' 'M177'
 'M180' 'M181' 'M185' 'M186' 'M188' 'M193' 'M194' 'M197' 'M55' 'M82' 'M99'
 'N105' 'N110' 'N124' 'N128' 'N129' 'N134' 'N136' 'N141' 'N15' 'N98' 'B41'
 'E116' 'E156' 'E198' 'E204' 'E82' 'F65' 'N117' 'N39' 'E105' 'N196' 'D69'
 'F154' 'M15' 'M84' 'C42' 'D48' 'F103' 'E112' 'F96' 'F143' 'M32' 'M69'
 'N32' 'N85' 'N86' 'A163' 'E230' 'F111' 'F114' 'F128' 'F136' 'F141' 'M212'
 'M43' 'N159' 'N163' 'N78' 'A146' 'A164' 'B63' 'F163' 'F46' 'F87' 'M11'
 'M137' 'M60' 'M66' 'N93' 'B111' 'B34' 'D17' 'D53' 'D60' 'D61' 'E202'
 'E216' 'E75' 'M124' 'M167' 'M192' 'N120' 'N140' 'N60' 'C15' 'C41' 'C60'
 'D25' 'D26' 'D34' 'D75' 'D76' 'E73' 'F142' 'M117' 'M16' 'M183' 'M40'
 'N102' 'N198' 'N70' 'B56' 'C11' 'C14' 'E24' 'M200' 'E113' 'E207' 'F177'
 'F44' 'M115' 'A47' 'E107' 'E183' 'F159' 'F19' 'M135' 'M195' 'M95' 'A20'
 'C23' 'D68' 'D84' 'D91' 'F54' 'M48' 'A153' 'E136' 'M83' 'A114' 'A62'
 'B110' 'B23' 'B70' 'E123' 'E233' 'E41' 'A142' 'A51' 'B118' 'B52' 'E166'
 'E213' 'F20' 'N35' 'A128' 'B33' 'E205' 'A162' 'B114' 'E192' 'E218' 'F157'
 'M109' 'M123' 'M143' 'M174' 'N114' 'N64' 'D64' 'B32' 'B53' 'D83' 'E150'
 'E17' 'M112' 'M78' 'N108' 'N135' 'N137' 'N87' 'E100' 'E101' 'E146' 'E176'
 'E184' 'E223' 'E42' 'E96' 'F30' 'F34' 'N31' 'N51' 'N38' 'A18' 'A58'
 'B115' 'B116' 'B21' 'E130' 'E76' 'F137' 'M120' 'M126' 'M130' 'M151'
 'M187' 'M23' 'M64' 'M81' 'N187' 'N76' 'B61' 'F122' 'F59' 'M131' 'B121'
 'B16' 'B26' 'B36' 'B49' 'C52' 'C53' 'D85' 'F31' 'F41' 'F43' 'N133' 'N69'
 'B129' 'E135' 'E160' 'E163' 'E172' 'E177' 'E191' 'F47' 'F56' 'M100'
 'E148' 'E182' 'E79' 'M122' 'M166' 'C33' 'F133' 'M71' 'M72' 'A123' 'A157'
 'A63' 'B124' 'D36' 'D59' 'N185' 'C63' 'E43' 'M25' 'A159' 'A21' 'D20'
 'E175' 'E178' 'M38' 'N180' 'N21' 'N28' 'N99' 'A155' 'A167' 'F15' 'F178'
 'M182' 'M29' 'A61' 'B12' 'B65' 'C25' 'N109' 'N144' 'A124' 'C39' 'C54'
 'D54' 'E129' 'E13' 'E40' 'E94' 'F127' 'F66' 'F91' 'N116' 'N197' 'A113'
 'B127' 'B128' 'B130' 'E138' 'E159' 'E167' 'E181' 'E77' 'E91' 'F53' 'F57'
 'M161' 'M171' 'M172' 'M175' 'M176' 'M19' 'N126' 'N131' 'N147' 'N148'
 'N149' 'N150' 'N151' 'N26' 'N29' 'N30' 'N40' 'N41' 'N42' 'N43' 'N44'
 'N47' 'N48' 'N55' 'N56' 'N61' 'N62' 'N79' 'N80' 'N83' 'N84' 'A131' 'A134'
 'D96' 'E193' 'E224' 'E241' 'F28' 'F35' 'F71' 'F86' 'M89' 'N17' 'N33'
 'A133' 'D90' 'E217' 'E242' 'F144' 'F23' 'F33' 'M62' 'M80' 'A125' 'C21'
 'C44' 'E152' 'E220' 'E30' 'E32' 'E49' 'E85' 'F14' 'N67' 'E56' 'E72' 'M28'
 'M47' 'E58' 'A135' 'A67' 'E157' 'M145' 'N14' 'A119' 'C50' 'C56' 'E134'
 'M125' 'M164' 'N188' 'A66' 'B119' 'B13' 'D24' 'E115' 'E225' 'F105' 'F107'
 'F131' 'M119' 'M13' 'M162' 'M92' 'N192' 'N22' 'B22' 'B37' 'C28' 'E196'
 'E199' 'E231' 'F12' 'F148' 'F39' 'M114' 'A150' 'B19' 'E44' 'E51' 'F17'
 'F180' 'F48' 'M160' 'M53' 'N158' 'N16' 'E16' 'F29' 'M67' 'N118' 'N193'
 'A143' 'A52' 'B11' 'C35' 'C61' 'D18' 'D19' 'D46' 'E61' 'F115' 'F88'
 'M102' 'M110' 'N101' 'N154' 'N156' 'N160' 'N170' 'N25' 'N81' 'N95' 'A122'
 'A132' 'A139' 'E140' 'F124' 'F126' 'F42' 'F69' 'M154' 'B59' 'C59' 'E34'
 'F132' 'F67' 'F78' 'M129' 'A13' 'A137' 'A161' 'A40' 'D16' 'D87' 'E200'
 'E219' 'F102' 'F32' 'F84' 'M108' 'N181' 'N66' 'N73' 'F22' 'N90' 'A138'
 'A54' 'D30' 'D38' 'D73' 'D81' 'E143' 'E189' 'E53' 'E66' 'F109' 'F120'
 'F164' 'F37' 'F60' 'M165' 'M210' 'N172' 'A26' 'A69' 'D14' 'E114' 'F116'
 'F119' 'F151' 'F68' 'N122' 'N164' 'N171' 'N200' 'N46' 'A35' 'A45' 'B125'
 'B75' 'E12' 'E126' 'F97' 'M198' 'N111' 'N179' 'E68' 'F38' 'M157' 'M173'
 'B29' 'B50' 'B54' 'B71' 'C19' 'C66' 'D12' 'D22' 'D63' 'D78' 'D89' 'E127'
 'E29' 'E35' 'M127' 'M199' 'M201' 'N139' 'N168' 'N173' 'N174' 'N178'
 'N183' 'N191' 'N23' 'A116' 'A24' 'C43' 'C46' 'D39' 'D58' 'D67' 'E158'
 'E22' 'E226' 'E28' 'E70' 'E84' 'E98' 'E99' 'F112' 'M163' 'N127' 'N19'
 'N49' 'N88' 'B117' 'B24' 'B76' 'C22' 'D11' 'D21' 'D43' 'E128' 'E145'
 'E153' 'E25' 'E47' 'E54' 'E63' 'E86' 'N166' 'B43' 'D71' 'F166' 'B31'
 'E125' 'E221' 'E59' 'F125' 'M147' 'C47' 'A43']
stations in a specefic bus line 1
len-of-go stations: 34
len-of-back stations: 34
len-of-go back stations: 0
first Station  [3169 '1' '1' 'go' '????-157-57' 51.731912 32.720558 'od' 'normal' 'no'] 3169
last Station  [1227 '1' '1' 'back' '????? ???????-1' 51.693389 32.640658 'od' 'normal'
 'no']
['A145' 'A148' 'A34' 'B25' 'C16' 'C62' 'C65' 'D23' 'D33' 'D35' 'D44' 'D92'
 'D94' 'E31' 'E52' 'E55' 'F82' 'M50' 'N11' 'N167' 'N54' 'N77']
transactions in line 1 plat A145
          CardID  LineCode       FDate   Time  plat
0      542446139         1  1398/06/23  24030  A145
1      542446139         1  1398/06/23  24030  A145
2     2620656172         1  1398/06/23  24302  A145
3     2620656172         1  1398/06/23  24302  A145
4     3446252780         1  1398/06/23  26200  A145
...          ...       ...         ...    ...   ...
1827  2505359876         1  1398/06/23  76412  A145
1828  2505359876         1  1398/06/23  76413  A145
1829  2505359876         1  1398/06/23  76413  A145
1830  3109163381         1  1398/06/23  76875  A145
1831  3109163381         1  1398/06/23  76875  A145

[1832 rows x 5 columns]
first row of the selected chunck :
 [542446139 1 '1398/06/23' 24030 'A145']
1832
t0 = 24030
ts = 76875
time_intervals 88
10min interval view
 for line 1 plat A145
 [[2.403e+04 0.000e+00]
 [2.463e+04 3.000e+00]
 [2.523e+04 0.000e+00]
 [2.583e+04 0.000e+00]
 [2.643e+04 2.000e+00]
 [2.703e+04 6.000e+01]
 [2.763e+04 1.200e+01]
 [2.823e+04 1.600e+01]
 [2.883e+04 8.000e+00]
 [2.943e+04 0.000e+00]
 [3.003e+04 1.800e+01]
 [3.063e+04 1.200e+01]
 [3.123e+04 3.800e+01]
 [3.183e+04 1.200e+01]
 [3.243e+04 0.000e+00]
 [3.303e+04 0.000e+00]
 [3.363e+04 0.000e+00]
 [3.423e+04 0.000e+00]
 [3.483e+04 0.000e+00]
 [3.543e+04 3.200e+01]
 [3.603e+04 7.800e+01]
 [3.663e+04 4.800e+01]
 [3.723e+04 6.800e+01]
 [3.783e+04 2.000e+01]
 [3.843e+04 1.200e+01]
 [3.903e+04 0.000e+00]
 [3.963e+04 1.000e+01]
 [4.023e+04 3.200e+01]
 [4.083e+04 4.800e+01]
 [4.143e+04 3.200e+01]
 [4.203e+04 7.600e+01]
 [4.263e+04 3.000e+01]
 [4.323e+04 2.200e+01]
 [4.383e+04 4.000e+00]
 [4.443e+04 6.600e+01]
 [4.503e+04 4.200e+01]
 [4.563e+04 2.600e+01]
 [4.623e+04 4.000e+01]
 [4.683e+04 3.000e+01]
 [4.743e+04 3.000e+01]
 [4.803e+04 2.000e+00]
 [4.863e+04 8.000e+00]
 [4.923e+04 2.200e+01]
 [4.983e+04 5.800e+01]
 [5.043e+04 7.000e+01]
 [5.103e+04 2.200e+01]
 [5.163e+04 6.000e+00]
 [5.223e+04 0.000e+00]
 [5.283e+04 0.000e+00]
 [5.343e+04 0.000e+00]
 [5.403e+04 0.000e+00]
 [5.463e+04 1.000e+01]
 [5.523e+04 5.800e+01]
 [5.583e+04 1.600e+01]
 [5.643e+04 1.400e+01]
 [5.703e+04 4.000e+00]
 [5.763e+04 2.000e+00]
 [5.823e+04 2.600e+01]
 [5.883e+04 3.800e+01]
 [5.943e+04 2.600e+01]
 [6.003e+04 1.400e+01]
 [6.063e+04 0.000e+00]
 [6.123e+04 0.000e+00]
 [6.183e+04 0.000e+00]
 [6.243e+04 0.000e+00]
 [6.303e+04 0.000e+00]
 [6.363e+04 0.000e+00]
 [6.423e+04 4.200e+01]
 [6.483e+04 6.200e+01]
 [6.543e+04 4.600e+01]
 [6.603e+04 3.000e+01]
 [6.663e+04 2.200e+01]
 [6.723e+04 1.600e+01]
 [6.783e+04 1.000e+01]
 [6.843e+04 1.800e+01]
 [6.903e+04 4.000e+01]
 [6.963e+04 3.400e+01]
 [7.023e+04 5.600e+01]
 [7.083e+04 3.600e+01]
 [7.143e+04 2.000e+01]
 [7.203e+04 1.400e+01]
 [7.263e+04 0.000e+00]
 [7.323e+04 0.000e+00]
 [7.383e+04 0.000e+00]
 [7.443e+04 1.400e+01]
 [7.503e+04 1.400e+01]
 [7.563e+04 1.000e+01]
 [7.623e+04 8.000e+00]]
Origin destination interval view
    time_in  time_out
0  24030.0   24630.0
1  25230.0   25830.0
2  29430.0   30030.0
3  32430.0   33030.0
4  39030.0   39630.0
5  52230.0   52830.0
6  60630.0   61230.0
7  72630.0   73230.0
OD bus stations of transactions:
         CardID  LineCode       FDate   Time  plat  Station
0    542446139         1  1398/06/23  24030  A145     3169
1    542446139         1  1398/06/23  24030  A145     3169
2   2620656172         1  1398/06/23  24302  A145     3169
3   2620656172         1  1398/06/23  24302  A145     3169
4      7900260         1  1398/06/23  29677  A145     3169
5      7900260         1  1398/06/23  29677  A145     3169
6    361857972         1  1398/06/23  29720  A145     3169
7    361857972         1  1398/06/23  29720  A145     3169
8   3603855420         1  1398/06/23  29728  A145     3169
9   3603855420         1  1398/06/23  29728  A145     3169
10  2740520628         1  1398/06/23  29739  A145     3169
11  2740520628         1  1398/06/23  29739  A145     3169
12  1407168786         1  1398/06/23  29801  A145     3169
13  1407168786         1  1398/06/23  29801  A145     3169
14  3672531922         1  1398/06/23  29837  A145     3169
15  3672531922         1  1398/06/23  29837  A145     3169
16  3206958021         1  1398/06/23  29840  A145     3169
17  3206958021         1  1398/06/23  29840  A145     3169
18  3794248044         1  1398/06/23  29858  A145     3169
19  3794248044         1  1398/06/23  29858  A145     3169
20  1002962247         1  1398/06/23  29964  A145     3169
21  1002962247         1  1398/06/23  29964  A145     3169
22   536831022         1  1398/06/23  39506  A145     3169
23   536831022         1  1398/06/23  39506  A145     3169
24  2742047524         1  1398/06/23  39532  A145     3169
25  2742047524         1  1398/06/23  39532  A145     3169
26  2742047524         1  1398/06/23  39533  A145     3169
27  2742047524         1  1398/06/23  39533  A145     3169
28  1528578990         1  1398/06/23  39582  A145     3169
29  1528578990         1  1398/06/23  39582  A145     3169
30   869232161         1  1398/06/23  39615  A145     3169
31   869232161         1  1398/06/23  39615  A145     3169
time_start time_stop 24630.0 25230.0
df_bus_partial :
 Empty DataFrame
Columns: [CardID, LineCode, FDate, Time, plat]
Index: []
Empty DataFrame
Columns: [Time, LineCode]
Index: []
time_start time_stop 25830.0 29430.0
df_bus_partial :
         CardID  LineCode       FDate   Time  plat
0   3446252780         1  1398/06/23  26200  A145
1   3446252780         1  1398/06/23  26200  A145
2   1281272526         1  1398/06/23  26446  A145
3   1281272526         1  1398/06/23  26446  A145
4    186286502         1  1398/06/23  26449  A145
..         ...       ...         ...    ...   ...
93  3677831388         1  1398/06/23  28240  A145
94  2125230308         1  1398/06/23  28342  A145
95  2125230308         1  1398/06/23  28342  A145
96   990427550         1  1398/06/23  28461  A145
97   990427550         1  1398/06/23  28461  A145

[98 rows x 5 columns]
     Time  LineCode
0   26200         1
1   26200         1
2   26446         1
3   26446         1
4   26449         1
..    ...       ...
93  28240         1
94  28342         1
95  28342         1
96  28461         1
97  28461         1

[98 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

kmeans.labels_ in go routes [ 6  6 23 23 23 23 23 23 33 33 33 33 33 33  3  3 21 21 28 28 15 15 15 15
 26 26 17 17 13 13 24 24 30 30 30 30 30 30  8  8  8  8  8  8  8  8  1  1
 32 32 27 27 22 22  9  9  9  9 16 16 16 16  5  5 12 12  0  0 25 25 31 31
 19 19 29 29 29 29  4  4 11 11 10 10 10 10 18 18 20 20  2  2  2  2 14 14
  7  7]
kmeansLabels
 [ 6 23 33  3 21 28 15 26 17 13 24 30  8  1 32 27 22  9 16  5 12  0 25 31
 19 29  4 11 10 18 20  2 14  7]
time_start time_stop 30030.0 32430.0
df_bus_partial :
         CardID  LineCode       FDate   Time  plat
0   2124848516         1  1398/06/23  30185  A145
1   2124848516         1  1398/06/23  30185  A145
2    186468982         1  1398/06/23  30453  A145
3    186468982         1  1398/06/23  30453  A145
4    869251094         1  1398/06/23  30508  A145
..         ...       ...         ...    ...   ...
57  2122551444         1  1398/06/23  31588  A145
58  2741114308         1  1398/06/23  31593  A145
59  2741114308         1  1398/06/23  31593  A145
60  3700626101         1  1398/06/23  31794  A145
61  3700626101         1  1398/06/23  31794  A145

[62 rows x 5 columns]
     Time  LineCode
0   30185         1
1   30185         1
2   30453         1
3   30453         1
4   30508         1
..    ...       ...
57  31588         1
58  31593         1
59  31593         1
60  31794         1
61  31794         1

[62 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 4  4  9  9 14 14 26 26  1  1 13 13  8  8 21 21 29 29  2  2 23 23 28 28
 17 17 20 20 12 12 15 15 15 15 22 22  5  5 11 11 27 27 24 24  0  0 18 18
 25 25 10 10 16 16  7  7 19 19  3  3  6  6]
kmeansLabels
 [ 4  9 14 26  1 13  8 21 29  2 23 28 17 20 12 15 22  5 11 27 24  0 18 25
 10 16  7 19  3  6]
time_start time_stop 33030.0 39030.0

<ipython-input-20-4e99cb401823>:165: ConvergenceWarning: Number of distinct clusters (30) found smaller than n_clusters (34). Possibly due to duplicate points in X.
  kmeans = KMeans(n_clusters=len(filter_go_stations),random_state=0, init='k-means++').fit(partial_times.to_numpy())

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    4278444658         1  1398/06/23  34926  A145
1    4278444658         1  1398/06/23  34926  A145
2     233143418         1  1398/06/23  34943  A145
3     233143418         1  1398/06/23  34943  A145
4    3793556588         1  1398/06/23  34956  A145
..          ...       ...         ...    ...   ...
253   426388334         1  1398/06/23  38137  A145
254  3603844156         1  1398/06/23  38258  A145
255  3603844156         1  1398/06/23  38258  A145
256  3793671436         1  1398/06/23  38291  A145
257  3793671436         1  1398/06/23  38291  A145

[258 rows x 5 columns]
      Time  LineCode
0    34926         1
1    34926         1
2    34943         1
3    34943         1
4    34956         1
..     ...       ...
253  38137         1
254  38258         1
255  38258         1
256  38291         1
257  38291         1

[258 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 5  5  5  5  5  5  5  5 23 23 23 23 12 12 12 12 12 12 12 12  9  9  9  9
  9  9  9  9  9  9  9  9  1  1  1  1  1  1  1  1  1  1  1  1 14 14 14 14
 14 14 14 14 14 14 14 14 14 14 17 17 17 17 17 17 17 17 17 17  7  7  7  7
  7  7  7  7 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21
 21 21 21 21 21 21  3  3  3  3  3  3  3  3 19 19 19 19 19 19 19 19 30 30
 30 30 10 10 10 10 10 10 10 10 20 20 20 20 29 29 29 29 29 29 29 29 29 29
 29 29 29 29  6  6 15 15 15 15 24 24 24 24 26 26 31 31 31 31 31 31  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 28 28 28 28 28 28 28 28 28 28 33 33
 33 33 16 16 16 16 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18 18 18 18 18 18 18  4  4 11 11 11 11 11 11 11 11 32 32  8  8  8  8
  8  8  8  8 25 25  2  2  2  2  2  2 27 27 13 13 13 13]
kmeansLabels
 [ 5 23 12  9  1 14 17  7 22 21  3 19 30 10 20 29  6 15 24 26 31  0 28 33
 16 18  4 11 32  8 25  2 27 13]
time_start time_stop 39630.0 52230.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    4057439869         1  1398/06/23  39722  A145
1    4057439869         1  1398/06/23  39722  A145
2     210511643         1  1398/06/23  39788  A145
3     210511643         1  1398/06/23  39788  A145
4     210511643         1  1398/06/23  39791  A145
..          ...       ...         ...    ...   ...
661  3180979262         1  1398/06/23  51075  A145
662  3180979262         1  1398/06/23  51076  A145
663  3180979262         1  1398/06/23  51076  A145
664  3648026404         1  1398/06/23  51472  A145
665  3648026404         1  1398/06/23  51472  A145

[666 rows x 5 columns]
      Time  LineCode
0    39722         1
1    39722         1
2    39788         1
3    39788         1
4    39791         1
..     ...       ...
661  51075         1
662  51076         1
663  51076         1
664  51472         1
665  51472         1

[666 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 19 19
 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
 30 30 30 30 30 30 30 30 30 30 11 11 11 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 16 16 16 16 16 16 16 16
 16 16 16 16 16 16 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6 27 27
 27 27 27 27 27 27 27 27 27 27 27 27 27 27 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 17 17 17 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 24 24 24 24 32 32 32 32 32 32 32 32  9  9  9  9  9  9  9  9  9  9  9  9
  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9
  9  9  9  9 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5 31 31 31 31 31 31 31 31 31 31
 15 15 15 15 15 15 15 15 25 25 25 25 25 25 25 25 25 25  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3 22 22 22 22
 22 22 22 22 22 22 22 22 22 22 22 22 28 28 28 28 28 28 28 28 28 28  8  8
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 13 13 13 13
 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 23 23 23 23  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 20 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 26 26 26 26 26 26 26 26 26 26
 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 18 18 14 14 14 14 14 14 14 14 14 14 14 14
 14 14 14 14  7  7  7  7  7  7  7  7  7  7  7  7 33 33]
kmeansLabels
 [10 19  2 30 11 16 21  6 27 17  0 24 32  9 29  5 31 15 25  3 22 28  8 13
 23  1 12 20 26  4 18 14  7 33]
time_start time_stop 52830.0 60630.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    2138001821         1  1398/06/23  54425  A145
1     869399875         1  1398/06/23  54425  A145
2    2138001821         1  1398/06/23  54425  A145
3     869399875         1  1398/06/23  54425  A145
4    2541747758         1  1398/06/23  54430  A145
..          ...       ...         ...    ...   ...
203   262484289         1  1398/06/23  59916  A145
204   262484289         1  1398/06/23  59918  A145
205   262484289         1  1398/06/23  59918  A145
206  2048171298         1  1398/06/23  60025  A145
207  2048171298         1  1398/06/23  60025  A145

[208 rows x 5 columns]
      Time  LineCode
0    54425         1
1    54425         1
2    54425         1
3    54425         1
4    54430         1
..     ...       ...
203  59916         1
204  59918         1
205  59918         1
206  60025         1
207  60025         1

[208 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 9  9  9  9  9  9 15 15 15 15 22 22 22 22 22 22 22 22  0  0  0  0  0  0
  0  0  0  0  0  0  0  0 11 11 11 11 11 11 11 11 11 11 11 11 11 11 31 31
 31 31 31 31 17 17 17 17 17 17 17 17 17 17 27 27 27 27 27 27 27 27 27 27
  5  5  5  5 33 33 16 16 16 16 16 16  6  6  6  6  2  2  2  2  2  2  2  2
 21 21 21 21 14 14 20 20  7  7  7  7  7  7  7  7 28 28  3  3 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 26 26 26 26 10 10 10 10 10 10 10 10 10 10
 23 23 23 23 23 23 23 23 23 23  1  1  1  1  1  1 24 24 24 24 24 24 24 24
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 19 19 25 25 25 25 12 12
 29 29 32 32  4  4  4  4 13 13 13 13 13 13 30 30]
kmeansLabels
 [ 9 15 22  0 11 31 17 27  5 33 16  6  2 21 14 20  7 28  3 18 26 10 23  1
 24  8 19 25 12 29 32  4 13 30]
time_start time_stop 61230.0 72630.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    1002545351         1  1398/06/23  63817  A145
1    1002545351         1  1398/06/23  63817  A145
2    3254145869         1  1398/06/23  63830  A145
3    3254145869         1  1398/06/23  63830  A145
4    3180738622         1  1398/06/23  63832  A145
..          ...       ...         ...    ...   ...
441   722164004         1  1398/06/23  71540  A145
442   722164004         1  1398/06/23  71544  A145
443   722164004         1  1398/06/23  71544  A145
444   736371680         1  1398/06/23  71569  A145
445   736371680         1  1398/06/23  71569  A145

[446 rows x 5 columns]
      Time  LineCode
0    63817         1
1    63817         1
2    63830         1
3    63830         1
4    63832         1
..     ...       ...
441  71540         1
442  71544         1
443  71544         1
444  71569         1
445  71569         1

[446 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14
 14 14 14 14  4  4  4  4  4  4  4  4  4  4  4  4  4  4 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20  8  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26
 26 26 26 26 26 26 26 26 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
 16 16  1  1  1  1  1  1 31 31 31 31 31 31 31 31 18 18 18 18 18 18 18 18
 18 18 18 18 18 18  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 11 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 27 27 27 27 27 27  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3 24 24 24 24 24 24 10 10 10 10  2  2  2  2  2  2  2  2  2  2  2  2
 21 21 21 21 21 21 21 21 21 21 21 21 28 28 28 28 28 28 28 28 28 28  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6 25 25
 25 25 25 25 25 25 25 25 25 25 13 13 13 13 13 13 13 13 29 29 29 29 29 29
 29 29 29 29 23 23 23 23 23 23 22 22 22 22 22 22 22 22 22 22  0  0  0  0
  0  0  0  0  0  0  0  0 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 32 32 32 32  9  9  9  9
  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9
 30 30 30 30 19 19 19 19 19 19 33 33 33 33 33 33  5  5  5  5  5  5  5  5
 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
kmeansLabels
 [14  4 20  8 26 16  1 31 18  7 12 11 27  3 24 10  2 21 28  6 25 13 29 23
 22  0 17 32  9 30 19 33  5 15]
transactions in line 1 plat A148
          CardID  LineCode       FDate   Time  plat
1832   212671675         1  1398/06/23  21811  A148
1833   212671675         1  1398/06/23  21811  A148
1834   426167598         1  1398/06/23  21850  A148
1835   426167598         1  1398/06/23  21850  A148
1836  2741717316         1  1398/06/23  21888  A148
...          ...       ...         ...    ...   ...
3461  2048218530         1  1398/06/23  78270  A148
3462  3166414222         1  1398/06/23  78276  A148
3463  3166414222         1  1398/06/23  78276  A148
3464   173733190         1  1398/06/23  78281  A148
3465   173733190         1  1398/06/23  78281  A148

[1634 rows x 5 columns]
first row of the selected chunck :
 [212671675 1 '1398/06/23' 21811 'A148']
1634
t0 = 21811
ts = 78281
time_intervals 94
10min interval view
 for line 1 plat A148
 [[2.1811e+04 0.0000e+00]
 [2.2411e+04 7.0000e+00]
 [2.3011e+04 4.0000e+00]
 [2.3611e+04 0.0000e+00]
 [2.4211e+04 0.0000e+00]
 [2.4811e+04 0.0000e+00]
 [2.5411e+04 0.0000e+00]
 [2.6011e+04 2.4000e+01]
 [2.6611e+04 8.0000e+01]
 [2.7211e+04 1.6000e+01]
 [2.7811e+04 8.0000e+00]
 [2.8411e+04 8.0000e+00]
 [2.9011e+04 0.0000e+00]
 [2.9611e+04 1.2000e+01]
 [3.0211e+04 1.2000e+01]
 [3.0811e+04 2.6000e+01]
 [3.1411e+04 1.2000e+01]
 [3.2011e+04 3.4000e+01]
 [3.2611e+04 0.0000e+00]
 [3.3211e+04 0.0000e+00]
 [3.3811e+04 0.0000e+00]
 [3.4411e+04 0.0000e+00]
 [3.5011e+04 2.4000e+01]
 [3.5611e+04 4.6000e+01]
 [3.6211e+04 5.2000e+01]
 [3.6811e+04 2.6000e+01]
 [3.7411e+04 4.6000e+01]
 [3.8011e+04 1.4000e+01]
 [3.8611e+04 1.8000e+01]
 [3.9211e+04 1.0000e+01]
 [3.9811e+04 5.4000e+01]
 [4.0411e+04 2.4000e+01]
 [4.1011e+04 4.0000e+01]
 [4.1611e+04 5.0000e+01]
 [4.2211e+04 4.6000e+01]
 [4.2811e+04 3.0000e+01]
 [4.3411e+04 2.0000e+00]
 [4.4011e+04 0.0000e+00]
 [4.4611e+04 1.0000e+01]
 [4.5211e+04 4.8000e+01]
 [4.5811e+04 2.0000e+01]
 [4.6411e+04 3.0000e+01]
 [4.7011e+04 3.0000e+01]
 [4.7611e+04 5.0000e+01]
 [4.8211e+04 1.6000e+01]
 [4.8811e+04 1.6000e+01]
 [4.9411e+04 2.4000e+01]
 [5.0011e+04 7.4000e+01]
 [5.0611e+04 1.8000e+01]
 [5.1211e+04 3.2000e+01]
 [5.1811e+04 2.0000e+00]
 [5.2411e+04 0.0000e+00]
 [5.3011e+04 0.0000e+00]
 [5.3611e+04 0.0000e+00]
 [5.4211e+04 8.0000e+00]
 [5.4811e+04 3.0000e+01]
 [5.5411e+04 8.0000e+00]
 [5.6011e+04 1.0000e+01]
 [5.6611e+04 4.0000e+00]
 [5.7211e+04 2.0000e+00]
 [5.7811e+04 1.2000e+01]
 [5.8411e+04 3.0000e+01]
 [5.9011e+04 1.6000e+01]
 [5.9611e+04 1.2000e+01]
 [6.0211e+04 2.0000e+00]
 [6.0811e+04 0.0000e+00]
 [6.1411e+04 0.0000e+00]
 [6.2011e+04 0.0000e+00]
 [6.2611e+04 0.0000e+00]
 [6.3211e+04 0.0000e+00]
 [6.3811e+04 2.2000e+01]
 [6.4411e+04 3.6000e+01]
 [6.5011e+04 8.0000e+00]
 [6.5611e+04 1.6000e+01]
 [6.6211e+04 2.4000e+01]
 [6.6811e+04 0.0000e+00]
 [6.7411e+04 1.6000e+01]
 [6.8011e+04 0.0000e+00]
 [6.8611e+04 1.4000e+01]
 [6.9211e+04 4.6000e+01]
 [6.9811e+04 4.0000e+01]
 [7.0411e+04 6.4000e+01]
 [7.1011e+04 2.4000e+01]
 [7.1611e+04 2.4000e+01]
 [7.2211e+04 1.8000e+01]
 [7.2811e+04 0.0000e+00]
 [7.3411e+04 0.0000e+00]
 [7.4011e+04 0.0000e+00]
 [7.4611e+04 0.0000e+00]
 [7.5211e+04 0.0000e+00]
 [7.5811e+04 1.4000e+01]
 [7.6411e+04 2.0000e+00]
 [7.7011e+04 4.0000e+00]
 [7.7611e+04 1.8000e+01]]
Origin destination interval view
    time_in  time_out
0  21811.0   22411.0
1  23611.0   24211.0
2  29011.0   29611.0
3  32611.0   33211.0
4  44011.0   44611.0
5  52411.0   53011.0
6  60811.0   61411.0
7  66811.0   67411.0
8  68011.0   68611.0
9  72811.0   73411.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

OD bus stations of transactions:
         CardID  LineCode       FDate   Time  plat  Station
0    212671675         1  1398/06/23  21811  A148     3169
1    212671675         1  1398/06/23  21811  A148     3169
2    426167598         1  1398/06/23  21850  A148     3169
3    426167598         1  1398/06/23  21850  A148     3169
4   2741717316         1  1398/06/23  21888  A148     3169
5   2741717316         1  1398/06/23  21888  A148     3169
6   3446907884         1  1398/06/23  22194  A148     3169
7   3446907884         1  1398/06/23  22194  A148     3169
8    721932446         1  1398/06/23  29381  A148     3169
9    721932446         1  1398/06/23  29381  A148     3169
10     8194356         1  1398/06/23  29455  A148     3169
11     8194356         1  1398/06/23  29455  A148     3169
12  3405836005         1  1398/06/23  29459  A148     3169
13  3405836005         1  1398/06/23  29459  A148     3169
14  3207894708         1  1398/06/23  29460  A148     3169
15  3207894708         1  1398/06/23  29460  A148     3169
16  3405963852         1  1398/06/23  29511  A148     3169
17  3405963852         1  1398/06/23  29511  A148     3169
18  3678579180         1  1398/06/23  29550  A148     3169
19  3678579180         1  1398/06/23  29550  A148     3169
20  3256118269         1  1398/06/23  44478  A148     3169
21  3256118269         1  1398/06/23  44478  A148     3169
22  2500450196         1  1398/06/23  44521  A148     3169
23  2500450196         1  1398/06/23  44521  A148     3169
24  2500450196         1  1398/06/23  44539  A148     3169
25  2500450196         1  1398/06/23  44539  A148     3169
26  3256118269         1  1398/06/23  44557  A148     3169
27  3256118269         1  1398/06/23  44557  A148     3169
28  3208569092         1  1398/06/23  44608  A148     3169
29  3208569092         1  1398/06/23  44608  A148     3169
30  1831436285         1  1398/06/23  66812  A148     1227
31  1831436285         1  1398/06/23  66812  A148     1227
32   261742385         1  1398/06/23  66841  A148     1227
33   261742385         1  1398/06/23  66841  A148     1227
34   261742385         1  1398/06/23  66842  A148     1227
35   261742385         1  1398/06/23  66842  A148     1227
36  1592714756         1  1398/06/23  66998  A148     1227
37  1592714756         1  1398/06/23  66998  A148     1227
38  1592714756         1  1398/06/23  67000  A148     1227
39  1592714756         1  1398/06/23  67000  A148     1227
40  3648982148         1  1398/06/23  67001  A148     1227
41  3648982148         1  1398/06/23  67001  A148     1227
42  3648982148         1  1398/06/23  67004  A148     1227
43  3648982148         1  1398/06/23  67004  A148     1227
44  2123598084         1  1398/06/23  67152  A148     1227
45  2123598084         1  1398/06/23  67152  A148     1227
46  3792548012         1  1398/06/23  68360  A148     3169
47  3792548012         1  1398/06/23  68360  A148     3169
48  1527873534         1  1398/06/23  68373  A148     3169
49  1527873534         1  1398/06/23  68373  A148     3169
50   869398503         1  1398/06/23  68405  A148     3169
51   869398503         1  1398/06/23  68405  A148     3169
52   869398503         1  1398/06/23  68406  A148     3169
53   869398503         1  1398/06/23  68406  A148     3169
54   869398503         1  1398/06/23  68408  A148     3169
55   869398503         1  1398/06/23  68408  A148     3169
56   869398503         1  1398/06/23  68409  A148     3169
57   869398503         1  1398/06/23  68409  A148     3169
58  1836298589         1  1398/06/23  68595  A148     3169
59  1836298589         1  1398/06/23  68595  A148     3169
time_start time_stop 22411.0 23611.0
df_bus_partial :
        CardID  LineCode       FDate   Time  plat
0  2044557086         1  1398/06/23  22444  A148
1  2044557086         1  1398/06/23  22444  A148
2  3997259316         1  1398/06/23  22602  A148
3  3997259316         1  1398/06/23  22602  A148
    Time  LineCode
0  22444         1
1  22444         1
2  22602         1
3  22602         1
time_start time_stop 24211.0 29011.0
df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0     426317438         1  1398/06/23  25810  A148
1     426317438         1  1398/06/23  25810  A148
2     869458586         1  1398/06/23  25816  A148
3    3258060013         1  1398/06/23  25816  A148
4    3258060013         1  1398/06/23  25816  A148
..          ...       ...         ...    ...   ...
131  3209686404         1  1398/06/23  28054  A148
132  3793530620         1  1398/06/23  28118  A148
133  3793530620         1  1398/06/23  28118  A148
134  2742417028         1  1398/06/23  28198  A148
135  2742417028         1  1398/06/23  28198  A148

[136 rows x 5 columns]
      Time  LineCode
0    25810         1
1    25810         1
2    25816         1
3    25816         1
4    25816         1
..     ...       ...
131  28054         1
132  28118         1
133  28118         1
134  28198         1
135  28198         1

[136 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

kmeans.labels_ in go routes [10 10 10 10 10 10 32 32 32 32 27 27 22 22 23 23 23 23  0  0  0  0 24 24
 30 30 30 30 30 30 30 30  8  8  8  8  8  8  8  8 33 33 16 16 16 16 16 16
 29 29 29 29 29 29  5  5  5  5  5  5  7  7  7  7  7  7  7  7 26 26 26 26
 26 26 26 26 26 26 14 14 14 14 14 14 25 25 28 28 28 28  2  2  2  2 31 31
 18 18 20 20  9  9  9  9  9  9 12 12 12 12 21 21  4  4 17 17 11 11 11 11
  1  1  1  1  1  1 13 13  6  6  3  3 19 19 15 15]
kmeansLabels
 [10 32 27 22 23  0 24 30  8 33 16 29  5  7 26 14 25 28  2 31 18 20  9 12
 21  4 17 11  1 13  6  3 19 15]
time_start time_stop 29611.0 32611.0
df_bus_partial :
         CardID  LineCode       FDate   Time  plat
0    722002745         1  1398/06/23  29713  A148
1    722002745         1  1398/06/23  29713  A148
2   3181087054         1  1398/06/23  29883  A148
3   3181087054         1  1398/06/23  29883  A148
4    261495729         1  1398/06/23  29885  A148
..         ...       ...         ...    ...   ...
79   722206394         1  1398/06/23  31870  A148
80   722206394         1  1398/06/23  31872  A148
81   722206394         1  1398/06/23  31872  A148
82   361275572         1  1398/06/23  31941  A148
83   361275572         1  1398/06/23  31941  A148

[84 rows x 5 columns]
     Time  LineCode
0   29713         1
1   29713         1
2   29883         1
3   29883         1
4   29885         1
..    ...       ...
79  31870         1
80  31872         1
81  31872         1
82  31941         1
83  31941         1

[84 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [10 10 28 28  3  3 24 24  7  7 14 14  6  6 32 32 13 13 23 23 23 23 23 23
  1  1  1  1  1  1 27 27 33 33 12 12 12 12  8  8 17 17 17 17  0  0  9  9
 15 15  5  5 31 31 25 25 20 20 21 21 26 26  2  2  2  2 22 22 19 19 16 16
 30 30  4  4  4  4 18 18 29 29 11 11]
kmeansLabels
 [10 28  3 24  7 14  6 32 13 23  1 27 33 12  8 17  0  9 15  5 31 25 20 21
 26  2 22 19 16 30  4 18 29 11]
time_start time_stop 33211.0 44011.0
df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    3181142334         1  1398/06/23  34670  A148
1    3181142334         1  1398/06/23  34670  A148
2     233543770         1  1398/06/23  34695  A148
3     233543770         1  1398/06/23  34695  A148
4     233543770         1  1398/06/23  34697  A148
..          ...       ...         ...    ...   ...
477   722027212         1  1398/06/23  42807  A148
478   722027212         1  1398/06/23  42808  A148
479   722027212         1  1398/06/23  42808  A148
480  3152188142         1  1398/06/23  42894  A148
481  3152188142         1  1398/06/23  42894  A148

[482 rows x 5 columns]
      Time  LineCode
0    34670         1
1    34670         1
2    34695         1
3    34695         1
4    34697         1
..     ...       ...
477  42807         1
478  42808         1
479  42808         1
480  42894         1
481  42894         1

[482 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32 32 32 32 32 32 32 32 32 32
 24 24 24 24 24 24 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 10 10
 10 10 10 10 10 10 10 10 10 10 28 28 28 28 28 28 28 28 28 28 28 28  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 22 22 22 22 22 22
 22 22 22 22 22 22 22 22 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2 31 31 31 31
 31 31 13 13 13 13 13 13 13 13 13 13 13 13 13 13 25 25 25 25 25 25 25 25
 25 25  6  6  6  6  6  6  6  6 26 26 26 26 26 26 26 26 26 26  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30  7  7
  7  7  7  7  7  7  7  7 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14
 14 14 29 29 29 29 29 29 19 19 19 19 19 19 23 23 23 23 23 23 23 23 23 23
 23 23 23 23  1  1  1  1  1  1  1  1  1  1  1  1  1  1 18 18 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18
 18 18  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 20 20 20 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 15 15 15 15 15 15 15 15
 15 15  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4 27 27 27 27
 27 27 27 27 27 27 27 27 27 27 11 11 11 11 11 11 11 11 21 21 21 21 21 21
 21 21]
kmeansLabels
 [16  0 32 24 33 10 28  5 22 12  9  2 31 13 25  6 26  3 17 30  7 14 29 19
 23  1 18  8 20 15  4 27 11 21]
time_start time_stop 44611.0 52411.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0     261517089         1  1398/06/23  44720  A148
1     261517089         1  1398/06/23  44720  A148
2    3180628798         1  1398/06/23  44731  A148
3    3180628798         1  1398/06/23  44731  A148
4     869425527         1  1398/06/23  44879  A148
..          ...       ...         ...    ...   ...
355   722188695         1  1398/06/23  51174  A148
356   722188695         1  1398/06/23  51175  A148
357   722188695         1  1398/06/23  51175  A148
358  3257409261         1  1398/06/23  51305  A148
359  3257409261         1  1398/06/23  51305  A148

[360 rows x 5 columns]
      Time  LineCode
0    44720         1
1    44720         1
2    44731         1
3    44731         1
4    44879         1
..     ...       ...
355  51174         1
356  51175         1
357  51175         1
358  51305         1
359  51305         1

[360 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [20 20 20 20 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24
  0  0  0  0  0  0  0  0  0  0 22 22 22 22 22 22 22 22 22 22 22 22 22 22
 32 32 10 10 10 10 10 10 10 10 10 10 10 10 10 10 29 29 29 29 13 13 13 13
 13 13 13 13 26 26 26 26 26 26 26 26  5  5  5  5  5  5  5  5  5  5 28 28
 28 28 14 14 14 14 14 14 14 14 14 14 14 14 14 14 30 30 30 30 30 30  2  2
  2  2  2  2  2  2  2  2 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
 21 21 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11
 31 31 31 31  7  7  7  7  7  7 17 17 17 17 17 17 16 16 16 16 16 16 16 16
 16 16  4  4 15 15 15 15 15 15 15 15 15 15 15 15 25 25 25 25 25 25 25 25
  8  8  8  8  8  8  8  8 23 23 23 23 23 23 23 23 23 23 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 33 33 33 33 33 33
 33 33 33 33 33 33  6  6  6  6  6  6  6  6  6  6  6  6  6  6 18 18 18 18
 18 18 18 18 18 18 18 18 18 18 18 18 18 18  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3 27 27 27 27 19 19 19 19  9  9  9  9  9  9  9  9]
kmeansLabels
 [20 24  0 22 32 10 29 13 26  5 28 14 30  2 21 11 31  7 17 16  4 15 25  8
 23 12  1 33  6 18  3 27 19  9]
time_start time_stop 53011.0 60811.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    1001609102         1  1398/06/23  53916  A148
1    1001609102         1  1398/06/23  53916  A148
2    4240952311         1  1398/06/23  54101  A148
3    4240952311         1  1398/06/23  54101  A148
4    3104649662         1  1398/06/23  54116  A148
..          ...       ...         ...    ...   ...
129  3152462414         1  1398/06/23  59514  A148
130  2124872724         1  1398/06/23  59608  A148
131  2124872724         1  1398/06/23  59608  A148
132  2961929781         1  1398/06/23  59784  A148
133  2961929781         1  1398/06/23  59784  A148

[134 rows x 5 columns]
      Time  LineCode
0    53916         1
1    53916         1
2    54101         1
3    54101         1
4    54116         1
..     ...       ...
129  59514         1
130  59608         1
131  59608         1
132  59784         1
133  59784         1

[134 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [17 17  6  6  6  6 16 16 16 16 16 16 27 27 30 30  2  2  2  2  2  2  2  2
 31 31 31 31 25 25 25 25 11 11 11 11 32 32 22 22 24 24 24 24  8  8  0  0
  0  0  0  0 13 13 13 13  5  5  5  5 18 18 10 10 10 10 10 10 29 29  4  4
 15 15 15 15 21 21 21 21  7  7  7  7  7  7  7  7 20 20 20 20 26 26 26 26
  1  1  1  1  1  1  1  1 19 19 19 19 19 19 12 12 12 12 12 12 23 23 23 23
  3  3 33 33  9  9  9  9  9  9 28 28 14 14]
kmeansLabels
 [17  6 16 27 30  2 31 25 11 32 22 24  8  0 13  5 18 10 29  4 15 21  7 20
 26  1 19 12 23  3 33  9 28 14]
time_start time_stop 61411.0 66811.0
df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    1001287422         1  1398/06/23  63508  A148
1    1001287422         1  1398/06/23  63508  A148
2    1001287422         1  1398/06/23  63509  A148
3    1001287422         1  1398/06/23  63509  A148
4     203071804         1  1398/06/23  63515  A148
..          ...       ...         ...    ...   ...
101  4059266269         1  1398/06/23  66172  A148
102  3208837700         1  1398/06/23  66175  A148
103  3631570396         1  1398/06/23  66175  A148
104  3208837700         1  1398/06/23  66175  A148
105  3631570396         1  1398/06/23  66175  A148

[106 rows x 5 columns]
      Time  LineCode
0    63508         1
1    63508         1
2    63509         1
3    63509         1
4    63515         1
..     ...       ...
101  66172         1
102  66175         1
103  66175         1
104  66175         1
105  66175         1

[106 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

kmeans.labels_ in go routes [25 25 25 25  3  3  3  3 27 27 16 16 33 33  8  8  8  8 21 21 21 21 22 22
 22 22  6  6  6  6  6  6 19 19 14 14 28 28 28 28  1  1 23 23 17 17 17 17
 32 32  9  9  9  9 31 31 20 20  4  4  4  4 13 13 10 10 12 12  2  2 11 11
 11 11 11 11 26 26 26 26  7  7 18 18 18 18 24 24 30 30  0  0  0  0  0  0
 15 15  5  5  5  5 29 29 29 29]
kmeansLabels
 [25  3 27 16 33  8 21 22  6 19 14 28  1 23 17 32  9 31 20  4 13 10 12  2
 11 26  7 18 24 30  0 15  5 29]
time_start time_stop 67411.0 68011.0
df_bus_partial :
 Empty DataFrame
Columns: [CardID, LineCode, FDate, Time, plat]
Index: []
Empty DataFrame
Columns: [Time, LineCode]
Index: []
time_start time_stop 68611.0 72811.0
df_bus_partial :
          CardID  LineCode       FDate   Time  plat
0    1764894068         1  1398/06/23  68722  A148
1    1764894068         1  1398/06/23  68722  A148
2    1845237556         1  1398/06/23  68804  A148
3    1845237556         1  1398/06/23  68804  A148
4     721937954         1  1398/06/23  68835  A148
..          ...       ...         ...    ...   ...
211   721968960         1  1398/06/23  71788  A148
212  3152288654         1  1398/06/23  71877  A148
213  3152288654         1  1398/06/23  71877  A148
214  2742453508         1  1398/06/23  71951  A148
215  2742453508         1  1398/06/23  71951  A148

[216 rows x 5 columns]
      Time  LineCode
0    68722         1
1    68722         1
2    68804         1
3    68804         1
4    68835         1
..     ...       ...
211  71788         1
212  71877         1
213  71877         1
214  71951         1
215  71951         1

[216 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [24 24 31 31  8  8  8  8  8  8 30 30  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4 28 28 28 28 28 28 28 28 19 19 19 19 19 19 19 19 19 19 16 16
 18 18 18 18  1  1  1  1  1  1 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 21 21 21 21 12 12 12 12 12 12 12 12 12 12 26 26 26 26 26 26 26 26 26 26
 26 26 26 26  6  6  6  6 33 33  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  7  7  7  7  7  7 29 29 29 29 29 29 29 29
 29 29 29 29 29 29 25 25 25 25 25 25 25 25 10 10 17 17 17 17 17 17 32 32
 32 32 32 32  0  0  9  9  9  9  9  9 14 14 14 14 20 20 20 20 20 20  3  3
 22 22 22 22 22 22 15 15 15 15 15 15  5  5  5  5 23 23 23 23 27 27 11 11]
kmeansLabels
 [24 31  8 30  4 28 19 16 18  1 13 21 12 26  6 33  2  7 29 25 10 17 32  0
  9 14 20  3 22 15  5 23 27 11]
transactions in line 1 plat A34
          CardID  LineCode       FDate   Time plat
3466  3254533261         1  1398/06/23  21100  A34
3467  3254533261         1  1398/06/23  21100  A34
3468  2499836756         1  1398/06/23  21379  A34
3469  2499836756         1  1398/06/23  21379  A34
3470  2672251844         1  1398/06/23  21516  A34
...          ...       ...         ...    ...  ...
4983  2855839198         1  1398/06/23  74899  A34
4984  3678152956         1  1398/06/23  75187  A34
4985  3678152956         1  1398/06/23  75187  A34
4986  3678152956         1  1398/06/23  75189  A34
4987  3678152956         1  1398/06/23  75189  A34

[1522 rows x 5 columns]
first row of the selected chunck :
 [3254533261 1 '1398/06/23' 21100 'A34']
1522
t0 = 21100
ts = 75189
time_intervals 90
10min interval view
 for line 1 plat A34
 [[2.11e+04 0.00e+00]
 [2.17e+04 5.00e+00]
 [2.23e+04 8.00e+00]
 [2.29e+04 0.00e+00]
 [2.35e+04 0.00e+00]
 [2.41e+04 0.00e+00]
 [2.47e+04 0.00e+00]
 [2.53e+04 1.80e+01]
 [2.59e+04 4.20e+01]
 [2.65e+04 2.20e+01]
 [2.71e+04 1.00e+01]
 [2.77e+04 0.00e+00]
 [2.83e+04 0.00e+00]
 [2.89e+04 2.40e+01]
 [2.95e+04 1.20e+01]
 [3.01e+04 1.80e+01]
 [3.07e+04 2.80e+01]
 [3.13e+04 2.00e+00]
 [3.19e+04 0.00e+00]
 [3.25e+04 0.00e+00]
 [3.31e+04 0.00e+00]
 [3.37e+04 2.20e+01]
 [3.43e+04 7.00e+01]
 [3.49e+04 5.20e+01]
 [3.55e+04 4.20e+01]
 [3.61e+04 1.60e+01]
 [3.67e+04 8.00e+00]
 [3.73e+04 0.00e+00]
 [3.79e+04 0.00e+00]
 [3.85e+04 2.60e+01]
 [3.91e+04 4.60e+01]
 [3.97e+04 3.60e+01]
 [4.03e+04 5.40e+01]
 [4.09e+04 2.80e+01]
 [4.15e+04 3.40e+01]
 [4.21e+04 4.00e+00]
 [4.27e+04 0.00e+00]
 [4.33e+04 0.00e+00]
 [4.39e+04 0.00e+00]
 [4.45e+04 0.00e+00]
 [4.51e+04 0.00e+00]
 [4.57e+04 0.00e+00]
 [4.63e+04 0.00e+00]
 [4.69e+04 4.00e+01]
 [4.75e+04 3.00e+01]
 [4.81e+04 1.20e+01]
 [4.87e+04 2.60e+01]
 [4.93e+04 4.00e+00]
 [4.99e+04 3.60e+01]
 [5.05e+04 2.60e+01]
 [5.11e+04 2.00e+01]
 [5.17e+04 1.00e+01]
 [5.23e+04 0.00e+00]
 [5.29e+04 4.00e+00]
 [5.35e+04 1.80e+01]
 [5.41e+04 6.00e+00]
 [5.47e+04 0.00e+00]
 [5.53e+04 0.00e+00]
 [5.59e+04 0.00e+00]
 [5.65e+04 2.80e+01]
 [5.71e+04 2.60e+01]
 [5.77e+04 1.60e+01]
 [5.83e+04 1.80e+01]
 [5.89e+04 0.00e+00]
 [5.95e+04 0.00e+00]
 [6.01e+04 0.00e+00]
 [6.07e+04 0.00e+00]
 [6.13e+04 0.00e+00]
 [6.19e+04 0.00e+00]
 [6.25e+04 1.60e+01]
 [6.31e+04 4.60e+01]
 [6.37e+04 5.20e+01]
 [6.43e+04 4.00e+01]
 [6.49e+04 1.40e+01]
 [6.55e+04 1.00e+01]
 [6.61e+04 8.00e+00]
 [6.67e+04 1.40e+01]
 [6.73e+04 4.00e+01]
 [6.79e+04 3.80e+01]
 [6.85e+04 3.80e+01]
 [6.91e+04 5.20e+01]
 [6.97e+04 3.60e+01]
 [7.03e+04 2.40e+01]
 [7.09e+04 4.00e+00]
 [7.15e+04 0.00e+00]
 [7.21e+04 2.40e+01]
 [7.27e+04 4.80e+01]
 [7.33e+04 1.40e+01]
 [7.39e+04 1.60e+01]
 [7.45e+04 2.80e+01]]
Origin destination interval view
    time_in  time_out
0  21100.0   21700.0
1  22900.0   23500.0
2  27700.0   28300.0
3  31900.0   32500.0
4  37300.0   37900.0
5  42700.0   43300.0
6  52300.0   52900.0
7  54700.0   55300.0
8  58900.0   59500.0
9  71500.0   72100.0
OD bus stations of transactions:
         CardID  LineCode       FDate   Time plat  Station
0   3254533261         1  1398/06/23  21100  A34     3169
1   3254533261         1  1398/06/23  21100  A34     3169
2   2499836756         1  1398/06/23  21379  A34     3169
3   2499836756         1  1398/06/23  21379  A34     3169
4   2672251844         1  1398/06/23  21516  A34     3169
5   2672251844         1  1398/06/23  21516  A34     3169
6    181815526         1  1398/06/23  52702  A34     3169
7    181815526         1  1398/06/23  52702  A34     3169
8    710482997         1  1398/06/23  52868  A34     3169
9    710482997         1  1398/06/23  52868  A34     3169
10   722125525         1  1398/06/23  71802  A34     1227
11   722125525         1  1398/06/23  71802  A34     1227
12   722125525         1  1398/06/23  71804  A34     1227
13   722125525         1  1398/06/23  71804  A34     1227
14  2039349402         1  1398/06/23  71808  A34     1227
15  2039349402         1  1398/06/23  71808  A34     1227
16  2742512068         1  1398/06/23  71810  A34     1227
17  2039349402         1  1398/06/23  71810  A34     1227
18  2742512068         1  1398/06/23  71810  A34     1227
19  2039349402         1  1398/06/23  71810  A34     1227
20  2742512068         1  1398/06/23  71811  A34     1227
21  2742512068         1  1398/06/23  71811  A34     1227
22   362181636         1  1398/06/23  71813  A34     1227
23   362181636         1  1398/06/23  71813  A34     1227
24  3152855710         1  1398/06/23  71819  A34     1227
25  3152855710         1  1398/06/23  71819  A34     1227
26   737781184         1  1398/06/23  71854  A34     1227
27   737781184         1  1398/06/23  71854  A34     1227
28   721938930         1  1398/06/23  71923  A34     1227
29   721938930         1  1398/06/23  71923  A34     1227
30  1093759220         1  1398/06/23  72095  A34     1227
31  1093759220         1  1398/06/23  72095  A34     1227
32  3202170164         1  1398/06/23  72099  A34     1227
33  3202170164         1  1398/06/23  72099  A34     1227
time_start time_stop 21700.0 22900.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
        CardID  LineCode       FDate   Time plat
0  2743407620         1  1398/06/23  21807  A34
1  2743407620         1  1398/06/23  21807  A34
2  3151648462         1  1398/06/23  21808  A34
3  3151648462         1  1398/06/23  21808  A34
4   233570410         1  1398/06/23  21905  A34
5   233570410         1  1398/06/23  21905  A34
6  2049418066         1  1398/06/23  22230  A34
7  2049418066         1  1398/06/23  22230  A34
    Time  LineCode
0  21807         1
1  21807         1
2  21808         1
3  21808         1
4  21905         1
5  21905         1
6  22230         1
7  22230         1
time_start time_stop 23500.0 27700.0
df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   3678775052         1  1398/06/23  24898  A34
1   3678775052         1  1398/06/23  24898  A34
2    257151153         1  1398/06/23  24918  A34
3    257151153         1  1398/06/23  24918  A34
4   2122381700         1  1398/06/23  24930  A34
..         ...       ...         ...    ...  ...
87   721938956         1  1398/06/23  26752  A34
88  2741219652         1  1398/06/23  26795  A34
89  2741219652         1  1398/06/23  26795  A34
90  1833177005         1  1398/06/23  27030  A34
91  1833177005         1  1398/06/23  27030  A34

[92 rows x 5 columns]
     Time  LineCode
0   24898         1
1   24898         1
2   24918         1
3   24918         1
4   24930         1
..    ...       ...
87  26752         1
88  26795         1
89  26795         1
90  27030         1
91  27030         1

[92 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [15 15 27 27 22 22 24 24  3  3  8  8  8  8  8  8 12 12 12 12 23 23 32 32
 32 32 30 30 30 30  1  1 28 28 13 13 13 13 31 31 10 10 33 33 25 25  4  4
 14 14 14 14 14 14  7  7 29 29 29 29 17 17 19 19  0  0  0  0  0  0 20 20
  9  9  5  5 26 26 26 26 16 16 18 18  2  2 21 21 11 11  6  6]
kmeansLabels
 [15 27 22 24  3  8 12 23 32 30  1 28 13 31 10 33 25  4 14  7 29 17 19  0
 20  9  5 26 16 18  2 21 11  6]
time_start time_stop 28300.0 31900.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   2229164291         1  1398/06/23  28319  A34
1   2229164291         1  1398/06/23  28319  A34
2   1292515038         1  1398/06/23  28325  A34
3   1292515038         1  1398/06/23  28325  A34
4   3405959994         1  1398/06/23  28330  A34
..         ...       ...         ...    ...  ...
79  3558258401         1  1398/06/23  30495  A34
80  4057328029         1  1398/06/23  30496  A34
81  4057328029         1  1398/06/23  30496  A34
82   721979470         1  1398/06/23  30744  A34
83   721979470         1  1398/06/23  30744  A34

[84 rows x 5 columns]
     Time  LineCode
0   28319         1
1   28319         1
2   28325         1
3   28325         1
4   28330         1
..    ...       ...
79  30495         1
80  30496         1
81  30496         1
82  30744         1
83  30744         1

[84 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [29 29  6  6 31 31 23 23 32 32 19 19 18 18 15 15  1  1 22 22 12 12  7  7
 25 25 27 27 27 27  3  3 13 13 17 17  8  8 28 28 28 28  0  0  0  0 24 24
 14 14 10 10 11 11 33 33 33 33 20 20 20 20  4  4 30 30 21 21 16 16  2  2
  2  2 26 26 26 26  9  9  9  9  5  5]
kmeansLabels
 [29  6 31 23 32 19 18 15  1 22 12  7 25 27  3 13 17  8 28  0 24 14 10 11
 33 20  4 30 21 16  2 26  9  5]
time_start time_stop 32500.0 37300.0
df_bus_partial :
          CardID  LineCode       FDate   Time plat
0    4265561938         1  1398/06/23  33440  A34
1    4265561938         1  1398/06/23  33440  A34
2     981290795         1  1398/06/23  33472  A34
3     981290795         1  1398/06/23  33472  A34
4     981290795         1  1398/06/23  33473  A34
..          ...       ...         ...    ...  ...
205  3154261054         1  1398/06/23  36381  A34
206  3207307589         1  1398/06/23  36384  A34
207  3207307589         1  1398/06/23  36384  A34
208  3792300860         1  1398/06/23  36465  A34
209  3792300860         1  1398/06/23  36465  A34

[210 rows x 5 columns]
      Time  LineCode
0    33440         1
1    33440         1
2    33472         1
3    33472         1
4    33473         1
..     ...       ...
205  36381         1
206  36384         1
207  36384         1
208  36465         1
209  36465         1

[210 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [27 27 32 32 32 32 32 32 32 32 12 12 12 12 12 12 23 23 23 23  0  0  8  8
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 20 20 20 20 30 30 30 30
 30 30  4  4 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 11 11
 11 11 11 11 11 11 29 29 29 29 17 17 17 17 17 17 17 17 17 17 33 33  2  2
  2  2  2  2  2  2 16 16 16 16 16 16 16 16 16 16 16 16 31 31 31 31 26 26
 18 18 21 21 21 21  5  5  5  5  5  5  5  5  5  5  5  5  5  5 22 22 22 22
 10 10 10 10 10 10 25 25 25 25 14 14 14 14 14 14  1  1  1  1 15 15  9  9
  9  9  9  9  9  9  9  9 28 28 28 28 28 28 28 28 28 28  7  7  7  7  7  7
  7  7  7  7  3  3  3  3  3  3  6  6 19 19 19 19 13 13]
kmeansLabels
 [27 32 12 23  0  8 20 30  4 24 11 29 17 33  2 16 31 26 18 21  5 22 10 25
 14  1 15  9 28  7  3  6 19 13]
time_start time_stop 37900.0 42700.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time plat
0    3678763084         1  1398/06/23  37975  A34
1     722234688         1  1398/06/23  37975  A34
2     722234688         1  1398/06/23  37975  A34
3    3678763084         1  1398/06/23  37975  A34
4    3678763084         1  1398/06/23  37977  A34
..          ...       ...         ...    ...  ...
223  3258303325         1  1398/06/23  41361  A34
224  3150896478         1  1398/06/23  41525  A34
225  3150896478         1  1398/06/23  41525  A34
226  2680566494         1  1398/06/23  41667  A34
227  2680566494         1  1398/06/23  41667  A34

[228 rows x 5 columns]
      Time  LineCode
0    37975         1
1    37975         1
2    37975         1
3    37975         1
4    37977         1
..     ...       ...
223  41361         1
224  41525         1
225  41525         1
226  41667         1
227  41667         1

[228 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 4  4  4  4  4  4  4  4  4  4  4  4  4  4 12 12 12 12 12 12 12 12 12 12
 16 16 27 27 27 27 27 27 31 31 31 31  2  2  2  2  2  2 22 22 22 22 22 22
 22 22 11 11 11 11 11 11 11 11 11 11  7  7  7  7  7  7 14 14 14 14 14 14
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32 32 21 21 24 24
 24 24 24 24 24 24 24 24 24 24 24 24  6  6 29 29  9  9  9  9  9  9  9  9
  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3 33 33 26 26 26 26 10 10 18 18 18 18
 18 18 30 30 25 25  1  1  1  1  1  1  1  1  1  1  1  1 23 23 23 23 17 17
 17 17 17 17 17 17  8  8  8  8 20 20 20 20 20 20 20 20 20 20 15 15 15 15
 28 28 28 28  5  5  5  5 19 19 13 13]
kmeansLabels
 [ 4 12 16 27 31  2 22 11  7 14  0 32 21 24  6 29  9  3 33 26 10 18 30 25
  1 23 17  8 20 15 28  5 19 13]
time_start time_stop 43300.0 52300.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time plat
0     869459594         1  1398/06/23  46334  A34
1     869459594         1  1398/06/23  46334  A34
2    3679839420         1  1398/06/23  46337  A34
3    3679839420         1  1398/06/23  46337  A34
4    3179643534         1  1398/06/23  46339  A34
..          ...       ...         ...    ...  ...
199  3632302268         1  1398/06/23  51307  A34
200  1958332228         1  1398/06/23  51309  A34
201  1958332228         1  1398/06/23  51309  A34
202  2855934286         1  1398/06/23  51312  A34
203  2855934286         1  1398/06/23  51312  A34

[204 rows x 5 columns]
      Time  LineCode
0    46334         1
1    46334         1
2    46337         1
3    46337         1
4    46339         1
..     ...       ...
199  51307         1
200  51309         1
201  51309         1
202  51312         1
203  51312         1

[204 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 13 13 13 13 13 13 13 13
 13 13  4  4  4  4 31 31 15 15 15 15 15 15 15 15 33 33 10 10 10 10 19 19
 19 19 25 25 25 25 25 25  1  1  1  1 27 27 27 27 27 27 27 27 27 27 16 16
 16 16  6  6  6  6  6  6  6  6 18 18 23 23 23 23 23 23  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  0  0  0  0 28 28 28 28 28 28 20 20
 20 20 29 29 29 29 12 12 21 21 21 21 30 30 30 30 30 30 30 30  9  9  9  9
  9  9  9  9 24 24 24 24 24 24  3  3 11 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 17 17 32 32 22 22 22 22  7  7  7  7 14 14 14 14 14 14 26 26
 26 26  2  2  2  2  2  2  2  2  2  2]
kmeansLabels
 [ 8 13  4 31 15 33 10 19 25  1 27 16  6 18 23  5  0 28 20 29 12 21 30  9
 24  3 11 17 32 22  7 14 26  2]
time_start time_stop 52900.0 54700.0
df_bus_partial :
         CardID  LineCode       FDate   Time plat
0    981231787         1  1398/06/23  53065  A34
1    981231787         1  1398/06/23  53065  A34
2    181938020         1  1398/06/23  53097  A34
3    181938020         1  1398/06/23  53097  A34
4    181938020         1  1398/06/23  53098  A34
5    181938020         1  1398/06/23  53098  A34
6   3206601100         1  1398/06/23  53258  A34
7   3206601100         1  1398/06/23  53258  A34
8   4270822914         1  1398/06/23  53364  A34
9   4270822914         1  1398/06/23  53364  A34
10   262396801         1  1398/06/23  53367  A34
11   262396801         1  1398/06/23  53367  A34
12  3256291661         1  1398/06/23  53386  A34
13  3256291661         1  1398/06/23  53386  A34
14  3405778345         1  1398/06/23  53426  A34
15  3405778345         1  1398/06/23  53426  A34
16  3405778345         1  1398/06/23  53432  A34
17  3405778345         1  1398/06/23  53432  A34
18   183411638         1  1398/06/23  53587  A34
19   183411638         1  1398/06/23  53587  A34
20   183411638         1  1398/06/23  53588  A34
21   183411638         1  1398/06/23  53588  A34
22   428719166         1  1398/06/23  54097  A34
23   428719166         1  1398/06/23  54097  A34
     Time  LineCode
0   53065         1
1   53065         1
2   53097         1
3   53097         1
4   53098         1
5   53098         1
6   53258         1
7   53258         1
8   53364         1
9   53364         1
10  53367         1
11  53367         1
12  53386         1
13  53386         1
14  53426         1
15  53426         1
16  53432         1
17  53432         1
18  53587         1
19  53587         1
20  53588         1
21  53588         1
22  54097         1
23  54097         1
time_start time_stop 55300.0 58900.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   3206072740         1  1398/06/23  56078  A34
1   3206072740         1  1398/06/23  56078  A34
2   3206072740         1  1398/06/23  56079  A34
3   3206072740         1  1398/06/23  56079  A34
4   2621769436         1  1398/06/23  56109  A34
..         ...       ...         ...    ...  ...
83  3206647516         1  1398/06/23  58078  A34
84  3206647516         1  1398/06/23  58254  A34
85  3206647516         1  1398/06/23  58254  A34
86  1003688919         1  1398/06/23  58274  A34
87  1003688919         1  1398/06/23  58274  A34

[88 rows x 5 columns]
     Time  LineCode
0   56078         1
1   56078         1
2   56079         1
3   56079         1
4   56109         1
..    ...       ...
83  58078         1
84  58254         1
85  58254         1
86  58274         1
87  58274         1

[88 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [20 20 20 20  4  4 28 28 26 26 14 14  6  6 27 27 27 27 31 31 31 31  9  9
  9  9 30 30 21 21  1  1  1  1 12 12 17 17 10 10 25 25 33 33  2  2 29 29
 29 29 16 16 16 16 11 11 15 15  7  7  7  7 23 23 19 19  0  0 22 22 13 13
  3  3  3  3 32 32 18 18 18 18  5  5 24 24  8  8]
kmeansLabels
 [20  4 28 26 14  6 27 31  9 30 21  1 12 17 10 25 33  2 29 16 11 15  7 23
 19  0 22 13  3 32 18  5 24  8]
time_start time_stop 59500.0 71500.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

df_bus_partial :
          CardID  LineCode       FDate   Time plat
0     184188806         1  1398/06/23  62282  A34
1     184188806         1  1398/06/23  62282  A34
2    3405884402         1  1398/06/23  62298  A34
3    3405884402         1  1398/06/23  62298  A34
4    1833384109         1  1398/06/23  62375  A34
..          ...       ...         ...    ...  ...
427  2505035236         1  1398/06/23  70281  A34
428   262668353         1  1398/06/23  70401  A34
429   262668353         1  1398/06/23  70401  A34
430  2239147470         1  1398/06/23  70523  A34
431  2239147470         1  1398/06/23  70523  A34

[432 rows x 5 columns]
      Time  LineCode
0    62282         1
1    62282         1
2    62298         1
3    62298         1
4    62375         1
..     ...       ...
427  70281         1
428  70401         1
429  70401         1
430  70523         1
431  70523         1

[432 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [11 11 11 11 28 28 28 28 28 28 28 28 28 28 28 28 25 25 25 25 25 25 25 25
 25 25 25 25 25 25  3  3  3  3  3  3  3  3  3  3  3  3 17 17 17 17 17 17
 17 17 17 17 17 17 17 17 17 17 17 17 17 17 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7 31 31 31 31 31 31
 31 31 31 31 22 22 22 22 22 22 22 22 22 22 22 22 22 22  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1 16 16 16 16 16 16 16 16 16 16 16 16 33 33
  6  6  6  6  6  6  6  6  6  6 15 15 15 15 15 15 15 15  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4 19 19 19 19 19 19 19 19 19 19 19 19 19 19
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8 20 20 20 20 20 20 20 20
 20 20 20 20 30 30 30 30 30 30 30 30  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2 29 29 29 29 29 29 29 29 29 29 13 13 13 13 18 18
 18 18 18 18 18 18 18 18 18 18 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 27 27 27 27 27 27 27 27
 27 27 27 27 27 27 27 27 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14
 14 14 14 14 14 14 14 14 32 32 32 32 32 32 32 32 23 23  0  0  0  0 24 24
 24 24 24 24 24 24 24 24  9  9  9  9  9  9  9  9  9  9  9  9 26 26 26 26]
kmeansLabels
 [11 28 25  3 17 12  7 31 22  1 16 33  6 15  4 19  8 20 30  2 29 13 18 10
 21  5 27 14 32 23  0 24  9 26]
transactions in line 1 plat B25
          CardID  LineCode       FDate   Time plat
4988  3405857235         1  1398/06/23  24232  B25
4989  3405857235         1  1398/06/23  24232  B25
4990   262238401         1  1398/06/23  24235  B25
4991   262238401         1  1398/06/23  24235  B25
4992  3792608284         1  1398/06/23  24237  B25
4993  3792608284         1  1398/06/23  24237  B25
4994  1001217566         1  1398/06/23  24260  B25
4995  1001217566         1  1398/06/23  24260  B25
4996  3258005613         1  1398/06/23  24264  B25
4997  3258005613         1  1398/06/23  24264  B25
4998  3446716236         1  1398/06/23  24314  B25
4999  3446716236         1  1398/06/23  24314  B25
5000  4059318045         1  1398/06/23  24332  B25
5001  4059318045         1  1398/06/23  24332  B25
5002   212456011         1  1398/06/23  24359  B25
5003   212456011         1  1398/06/23  24359  B25
5004   537939870         1  1398/06/23  24520  B25
5005   537939870         1  1398/06/23  24520  B25
5006  3996810372         1  1398/06/23  24525  B25
5007  3996810372         1  1398/06/23  24525  B25
5008  3794217068         1  1398/06/23  24586  B25
5009  3794217068         1  1398/06/23  24586  B25
5010   234290778         1  1398/06/23  24629  B25
5011   234290778         1  1398/06/23  24629  B25
5012  2740601460         1  1398/06/23  24641  B25
5013  2740601460         1  1398/06/23  24641  B25
5014  2497977524         1  1398/06/23  24643  B25
5015  2497977524         1  1398/06/23  24643  B25
5016  3648975444         1  1398/06/23  24646  B25
5017  3648975444         1  1398/06/23  24646  B25
5018  2125830612         1  1398/06/23  24978  B25
5019  2125830612         1  1398/06/23  24978  B25
5020  3680292124         1  1398/06/23  25403  B25
5021  3680292124         1  1398/06/23  25403  B25
5022  2115521716         1  1398/06/23  25517  B25
5023  2115521716         1  1398/06/23  25517  B25
5024   980735675         1  1398/06/23  25795  B25
5025   980735675         1  1398/06/23  25795  B25
5026  1528046382         1  1398/06/23  27458  B25
5027  1528046382         1  1398/06/23  27458  B25
5028   722133212         1  1398/06/23  27459  B25
5029   722133212         1  1398/06/23  27459  B25
5030  1291390174         1  1398/06/23  27470  B25
5031  1291390174         1  1398/06/23  27470  B25
5032  1371741102         1  1398/06/23  27474  B25
5033  1371741102         1  1398/06/23  27474  B25
5034  4276487330         1  1398/06/23  27476  B25
5035  4276487330         1  1398/06/23  27476  B25
first row of the selected chunck :
 [3405857235 1 '1398/06/23' 24232 'B25']
48
t0 = 24232
ts = 27476
time_intervals 5
10min interval view
 for line 1 plat B25
 [[2.4232e+04 0.0000e+00]
 [2.4832e+04 2.9000e+01]
 [2.5432e+04 4.0000e+00]
 [2.6032e+04 4.0000e+00]
 [2.6632e+04 0.0000e+00]]
Origin destination interval view
    time_in  time_out
0  24232.0   24832.0
1  26632.0   27232.0
OD bus stations of transactions:
         CardID  LineCode       FDate   Time plat  Station
0   3405857235         1  1398/06/23  24232  B25     3169
1   3405857235         1  1398/06/23  24232  B25     3169
2    262238401         1  1398/06/23  24235  B25     3169
3    262238401         1  1398/06/23  24235  B25     3169
4   3792608284         1  1398/06/23  24237  B25     3169
5   3792608284         1  1398/06/23  24237  B25     3169
6   1001217566         1  1398/06/23  24260  B25     3169
7   1001217566         1  1398/06/23  24260  B25     3169
8   3258005613         1  1398/06/23  24264  B25     3169
9   3258005613         1  1398/06/23  24264  B25     3169
10  3446716236         1  1398/06/23  24314  B25     3169
11  3446716236         1  1398/06/23  24314  B25     3169
12  4059318045         1  1398/06/23  24332  B25     3169
13  4059318045         1  1398/06/23  24332  B25     3169
14   212456011         1  1398/06/23  24359  B25     3169
15   212456011         1  1398/06/23  24359  B25     3169
16   537939870         1  1398/06/23  24520  B25     3169
17   537939870         1  1398/06/23  24520  B25     3169
18  3996810372         1  1398/06/23  24525  B25     3169
19  3996810372         1  1398/06/23  24525  B25     3169
20  3794217068         1  1398/06/23  24586  B25     3169
21  3794217068         1  1398/06/23  24586  B25     3169
22   234290778         1  1398/06/23  24629  B25     3169
23   234290778         1  1398/06/23  24629  B25     3169
24  2740601460         1  1398/06/23  24641  B25     3169
25  2740601460         1  1398/06/23  24641  B25     3169
26  2497977524         1  1398/06/23  24643  B25     3169
27  2497977524         1  1398/06/23  24643  B25     3169
28  3648975444         1  1398/06/23  24646  B25     3169
29  3648975444         1  1398/06/23  24646  B25     3169
time_start time_stop 24832.0 26632.0
df_bus_partial :
        CardID  LineCode       FDate   Time plat
0  2125830612         1  1398/06/23  24978  B25
1  2125830612         1  1398/06/23  24978  B25
2  3680292124         1  1398/06/23  25403  B25
3  3680292124         1  1398/06/23  25403  B25
4  2115521716         1  1398/06/23  25517  B25
5  2115521716         1  1398/06/23  25517  B25
6   980735675         1  1398/06/23  25795  B25
7   980735675         1  1398/06/23  25795  B25
    Time  LineCode
0  24978         1
1  24978         1
2  25403         1
3  25403         1
4  25517         1
5  25517         1
6  25795         1
7  25795         1
transactions in line 1 plat C16

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

          CardID  LineCode       FDate   Time plat
5036   722090946         1  1398/06/23  21377  C16
5037   722090946         1  1398/06/23  21377  C16
5038  2117203508         1  1398/06/23  21389  C16
5039  2117203508         1  1398/06/23  21389  C16
5040  2680053934         1  1398/06/23  21532  C16
...          ...       ...         ...    ...  ...
5679  3701415973         1  1398/06/23  74329  C16
5680  3701415973         1  1398/06/23  74330  C16
5681  3701415973         1  1398/06/23  74330  C16
5682  1368123646         1  1398/06/23  77137  C16
5683  1368123646         1  1398/06/23  77137  C16

[648 rows x 5 columns]
first row of the selected chunck :
 [722090946 1 '1398/06/23' 21377 'C16']
648
t0 = 21377
ts = 77137
time_intervals 93
10min interval view
 for line 1 plat C16
 [[2.1377e+04 0.0000e+00]
 [2.1977e+04 1.3000e+01]
 [2.2577e+04 2.0000e+00]
 [2.3177e+04 0.0000e+00]
 [2.3777e+04 0.0000e+00]
 [2.4377e+04 0.0000e+00]
 [2.4977e+04 1.0000e+01]
 [2.5577e+04 2.0000e+01]
 [2.6177e+04 4.0000e+00]
 [2.6777e+04 6.0000e+00]
 [2.7377e+04 0.0000e+00]
 [2.7977e+04 0.0000e+00]
 [2.8577e+04 4.2000e+01]
 [2.9177e+04 3.4000e+01]
 [2.9777e+04 0.0000e+00]
 [3.0377e+04 0.0000e+00]
 [3.0977e+04 0.0000e+00]
 [3.1577e+04 0.0000e+00]
 [3.2177e+04 0.0000e+00]
 [3.2777e+04 0.0000e+00]
 [3.3377e+04 0.0000e+00]
 [3.3977e+04 0.0000e+00]
 [3.4577e+04 0.0000e+00]
 [3.5177e+04 0.0000e+00]
 [3.5777e+04 0.0000e+00]
 [3.6377e+04 0.0000e+00]
 [3.6977e+04 0.0000e+00]
 [3.7577e+04 0.0000e+00]
 [3.8177e+04 0.0000e+00]
 [3.8777e+04 0.0000e+00]
 [3.9377e+04 0.0000e+00]
 [3.9977e+04 0.0000e+00]
 [4.0577e+04 0.0000e+00]
 [4.1177e+04 0.0000e+00]
 [4.1777e+04 0.0000e+00]
 [4.2377e+04 0.0000e+00]
 [4.2977e+04 0.0000e+00]
 [4.3577e+04 0.0000e+00]
 [4.4177e+04 0.0000e+00]
 [4.4777e+04 0.0000e+00]
 [4.5377e+04 0.0000e+00]
 [4.5977e+04 0.0000e+00]
 [4.6577e+04 0.0000e+00]
 [4.7177e+04 0.0000e+00]
 [4.7777e+04 0.0000e+00]
 [4.8377e+04 0.0000e+00]
 [4.8977e+04 0.0000e+00]
 [4.9577e+04 0.0000e+00]
 [5.0177e+04 0.0000e+00]
 [5.0777e+04 0.0000e+00]
 [5.1377e+04 0.0000e+00]
 [5.1977e+04 0.0000e+00]
 [5.2577e+04 0.0000e+00]
 [5.3177e+04 0.0000e+00]
 [5.3777e+04 0.0000e+00]
 [5.4377e+04 0.0000e+00]
 [5.4977e+04 0.0000e+00]
 [5.5577e+04 0.0000e+00]
 [5.6177e+04 0.0000e+00]
 [5.6777e+04 0.0000e+00]
 [5.7377e+04 0.0000e+00]
 [5.7977e+04 0.0000e+00]
 [5.8577e+04 0.0000e+00]
 [5.9177e+04 0.0000e+00]
 [5.9777e+04 0.0000e+00]
 [6.0377e+04 0.0000e+00]
 [6.0977e+04 2.4000e+01]
 [6.1577e+04 2.2000e+01]
 [6.2177e+04 1.2000e+01]
 [6.2777e+04 2.0000e+00]
 [6.3377e+04 0.0000e+00]
 [6.3977e+04 0.0000e+00]
 [6.4577e+04 0.0000e+00]
 [6.5177e+04 0.0000e+00]
 [6.5777e+04 1.0000e+01]
 [6.6377e+04 2.4000e+01]
 [6.6977e+04 5.8000e+01]
 [6.7577e+04 3.2000e+01]
 [6.8177e+04 2.4000e+01]
 [6.8777e+04 4.0000e+01]
 [6.9377e+04 2.0000e+00]
 [6.9977e+04 0.0000e+00]
 [7.0577e+04 0.0000e+00]
 [7.1177e+04 1.0000e+01]
 [7.1777e+04 5.8000e+01]
 [7.2377e+04 4.0000e+01]
 [7.2977e+04 5.4000e+01]
 [7.3577e+04 5.0000e+01]
 [7.4177e+04 2.8000e+01]
 [7.4777e+04 2.4000e+01]
 [7.5377e+04 0.0000e+00]
 [7.5977e+04 0.0000e+00]
 [7.6577e+04 0.0000e+00]]
Origin destination interval view
    time_in  time_out
0  21377.0   21977.0
1  23177.0   23777.0
2  27377.0   27977.0
3  29777.0   30377.0
4  63377.0   63977.0
5  69977.0   70577.0
6  75377.0   75977.0
OD bus stations of transactions:
         CardID  LineCode       FDate   Time plat  Station
0    722090946         1  1398/06/23  21377  C16     3169
1    722090946         1  1398/06/23  21377  C16     3169
2   2117203508         1  1398/06/23  21389  C16     3169
3   2117203508         1  1398/06/23  21389  C16     3169
4   2680053934         1  1398/06/23  21532  C16     3169
5   2680053934         1  1398/06/23  21532  C16     3169
6   2124941188         1  1398/06/23  21872  C16     3169
7   2124941188         1  1398/06/23  21872  C16     3169
8   1528649022         1  1398/06/23  21874  C16     3169
9   1528649022         1  1398/06/23  21874  C16     3169
10   212337004         1  1398/06/23  21911  C16     3169
11   212337004         1  1398/06/23  21911  C16     3169
12  2123505492         1  1398/06/23  21913  C16     3169
13  2123505492         1  1398/06/23  21913  C16     3169
time_start time_stop 21977.0 23177.0
df_bus_partial :
        CardID  LineCode       FDate   Time plat
0  2138368061         1  1398/06/23  22008  C16
1  2138368061         1  1398/06/23  22008  C16
    Time  LineCode
0  22008         1
1  22008         1
time_start time_stop 23777.0 27377.0
df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   3792026972         1  1398/06/23  24519  C16
1   3792026972         1  1398/06/23  24519  C16
2    869442828         1  1398/06/23  24565  C16
3    869442828         1  1398/06/23  24565  C16
4    722214742         1  1398/06/23  24601  C16
5    722214742         1  1398/06/23  24601  C16
6   3183170606         1  1398/06/23  24712  C16
7   3183170606         1  1398/06/23  24712  C16
8   3630510508         1  1398/06/23  24772  C16
9   3630510508         1  1398/06/23  24772  C16
10  2044923534         1  1398/06/23  25029  C16
11  2044923534         1  1398/06/23  25029  C16
12   343062692         1  1398/06/23  25100  C16
13   343062692         1  1398/06/23  25100  C16
14  1944196997         1  1398/06/23  25108  C16
15  1944196997         1  1398/06/23  25108  C16
16  3211506388         1  1398/06/23  25178  C16
17  3211506388         1  1398/06/23  25178  C16
18  3211506388         1  1398/06/23  25179  C16
19  3211506388         1  1398/06/23  25179  C16
20   983696571         1  1398/06/23  25184  C16
21   983696571         1  1398/06/23  25184  C16
22  1835758557         1  1398/06/23  25234  C16
23  1835758557         1  1398/06/23  25234  C16
24  1002165159         1  1398/06/23  25437  C16
25  1002165159         1  1398/06/23  25437  C16
26   981263643         1  1398/06/23  25476  C16
27   981263643         1  1398/06/23  25476  C16
28   869365619         1  1398/06/23  25478  C16
29   869365619         1  1398/06/23  25478  C16
30  3547393636         1  1398/06/23  25578  C16
31  3547393636         1  1398/06/23  25578  C16
32  3107363509         1  1398/06/23  25582  C16
33  3107363509         1  1398/06/23  25582  C16
34   722093142         1  1398/06/23  26259  C16
35   722093142         1  1398/06/23  26259  C16
36  3650336804         1  1398/06/23  26265  C16
37  3650336804         1  1398/06/23  26265  C16
38   737207232         1  1398/06/23  26432  C16
39   737207232         1  1398/06/23  26432  C16
     Time  LineCode
0   24519         1
1   24519         1
2   24565         1
3   24565         1
4   24601         1
5   24601         1
6   24712         1
7   24712         1
8   24772         1
9   24772         1
10  25029         1
11  25029         1
12  25100         1
13  25100         1
14  25108         1
15  25108         1
16  25178         1
17  25178         1
18  25179         1
19  25179         1
20  25184         1
21  25184         1
22  25234         1
23  25234         1
24  25437         1
25  25437         1
26  25476         1
27  25476         1
28  25478         1
29  25478         1
30  25578         1
31  25578         1
32  25582         1
33  25582         1
34  26259         1
35  26259         1
36  26265         1
37  26265         1
38  26432         1
39  26432         1
if(len(df_bus_partial) >=len(filter_go_stations))

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
<ipython-input-20-4e99cb401823>:165: ConvergenceWarning: Number of distinct clusters (20) found smaller than n_clusters (34). Possibly due to duplicate points in X.
  kmeans = KMeans(n_clusters=len(filter_go_stations),random_state=0, init='k-means++').fit(partial_times.to_numpy())
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

kmeans.labels_ in go routes [ 0  0 30 30 12 12 10 10  5  5 25 25 22 22 14 14  7  7 19 19 16 16 11 11
 13 13  4  4 18 18 17 17  1  1  2  2 15 15  3  3]
kmeansLabels
 [ 0 30 12 10  5 25 22 14  7 19 16 11 13  4 18 17  1  2 15  3]
time_start time_stop 27977.0 29777.0
df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   1832647869         1  1398/06/23  28131  C16
1   1832647869         1  1398/06/23  28131  C16
2   2239165765         1  1398/06/23  28181  C16
3   2239165765         1  1398/06/23  28181  C16
4   2122964020         1  1398/06/23  28202  C16
..         ...       ...         ...    ...  ...
71  1524902612         1  1398/06/23  28599  C16
72  1782169844         1  1398/06/23  28600  C16
73  1782169844         1  1398/06/23  28600  C16
74  1598567700         1  1398/06/23  28602  C16
75  1598567700         1  1398/06/23  28602  C16

[76 rows x 5 columns]
     Time  LineCode
0   28131         1
1   28131         1
2   28181         1
3   28181         1
4   28202         1
..    ...       ...
71  28599         1
72  28600         1
73  28600         1
74  28602         1
75  28602         1

[76 rows x 2 columns]
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 5  5  4  4 26 26 10 10  6  6 17 17 11 11  1  1 12 12  3  3 19 19 25 25
 27 27  0  0 29 29 30 30  8  8  8  8 24 24 32 32 14 14 21 21  7  7  7  7
 15 15 15 15 31 31 23 23 13 13 13 13  9  9 20 20 28 28 16 16  2  2 33 33
 22 22 18 18]
kmeansLabels
 [ 5  4 26 10  6 17 11  1 12  3 19 25 27  0 29 30  8 24 32 14 21  7 15 31
 23 13  9 20 28 16  2 33 22 18]
time_start time_stop 30377.0 63377.0
df_bus_partial :
         CardID  LineCode       FDate   Time plat
0   4058375165         1  1398/06/23  60428  C16
1   4058375165         1  1398/06/23  60428  C16
2   4275106514         1  1398/06/23  60433  C16
3   4275106514         1  1398/06/23  60433  C16
4   3180373134         1  1398/06/23  60457  C16
5   3180373134         1  1398/06/23  60457  C16
6    721790998         1  1398/06/23  60524  C16
7    721790998         1  1398/06/23  60524  C16
8   2230787619         1  1398/06/23  60570  C16
9   2230787619         1  1398/06/23  60570  C16
10   996526030         1  1398/06/23  60574  C16
11   996526030         1  1398/06/23  60574  C16
12  3257493277         1  1398/06/23  60585  C16
13  3257493277         1  1398/06/23  60585  C16
14  3700637749         1  1398/06/23  60627  C16
15  3700637749         1  1398/06/23  60627  C16
16  3977321124         1  1398/06/23  60711  C16
17  3977321124         1  1398/06/23  60711  C16
18  3792875548         1  1398/06/23  60841  C16
19  3792875548         1  1398/06/23  60841  C16
20  3632282812         1  1398/06/23  60879  C16
21  3632282812         1  1398/06/23  60879  C16
22  2504958948         1  1398/06/23  60938  C16
23  2504958948         1  1398/06/23  60938  C16
24   235220474         1  1398/06/23  60983  C16
25   235220474         1  1398/06/23  60983  C16
26   473741562         1  1398/06/23  60988  C16
27   473741562         1  1398/06/23  60988  C16
28   722010097         1  1398/06/23  61140  C16
29   722010097         1  1398/06/23  61140  C16
30  1368369278         1  1398/06/23  61146  C16
31  1368369278         1  1398/06/23  61146  C16
32  3150594126         1  1398/06/23  61198  C16
33  3150594126         1  1398/06/23  61198  C16
34   361082916         1  1398/06/23  61201  C16
35   361082916         1  1398/06/23  61201  C16
36   982474971         1  1398/06/23  61206  C16
37   982474971         1  1398/06/23  61206  C16
38   212395676         1  1398/06/23  61207  C16
39   212395676         1  1398/06/23  61207  C16
40   212395676         1  1398/06/23  61208  C16
41   212395676         1  1398/06/23  61208  C16
42   262279569         1  1398/06/23  61353  C16
43   262279569         1  1398/06/23  61353  C16
44  3258327325         1  1398/06/23  61477  C16
45  3258327325         1  1398/06/23  61477  C16
46  2239171815         1  1398/06/23  61652  C16
47  2239171815         1  1398/06/23  61652  C16
48   209428427         1  1398/06/23  61760  C16
49   209428427         1  1398/06/23  61760  C16
50   183343862         1  1398/06/23  61836  C16
51   183343862         1  1398/06/23  61836  C16
52  4058932589         1  1398/06/23  61837  C16
53  4058932589         1  1398/06/23  61837  C16
54  2541396686         1  1398/06/23  61972  C16
55  2541396686         1  1398/06/23  61972  C16
56  3758253541         1  1398/06/23  61980  C16
57  3758253541         1  1398/06/23  61980  C16
58  1957795460         1  1398/06/23  62369  C16
59  1957795460         1  1398/06/23  62369  C16
     Time  LineCode
0   60428         1
1   60428         1
2   60433         1
3   60433         1
4   60457         1
5   60457         1
6   60524         1
7   60524         1
8   60570         1
9   60570         1
10  60574         1
11  60574         1
12  60585         1
13  60585         1
14  60627         1
15  60627         1
16  60711         1
17  60711         1
18  60841         1
19  60841         1
20  60879         1
21  60879         1
22  60938         1
23  60938         1
24  60983         1
25  60983         1
26  60988         1
27  60988         1
28  61140         1
29  61140         1
30  61146         1
31  61146         1
32  61198         1
33  61198         1
34  61201         1
35  61201         1
36  61206         1
37  61206         1
38  61207         1
39  61207         1
40  61208         1
41  61208         1
42  61353         1
43  61353         1
44  61477         1
45  61477         1
46  61652         1
47  61652         1
48  61760         1
49  61760         1
50  61836         1
51  61836         1
52  61837         1
53  61837         1
54  61972         1
55  61972         1
56  61980         1
57  61980         1
58  62369         1
59  62369         1
if(len(df_bus_partial) >=len(filter_go_stations))
kmeans.labels_ in go routes [ 6  6 23 23 18 18 15 15 19 19 25 25 12 12  1  1 14 14 17 17  5  5 16 16
 24 24 10 10  3  3 22 22 20 20 26 26  9  9 29 29 27 27 11 11  0  0 13 13
  7  7  2  2 28 28 21 21  8  8  4  4]
kmeansLabels
 [ 6 23 18 15 19 25 12  1 14 17  5 16 24 10  3 22 20 26  9 29 27 11  0 13
  7  2 28 21  8  4]
time_start time_stop 63977.0 69977.0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
<ipython-input-20-4e99cb401823>:165: ConvergenceWarning: Number of distinct clusters (30) found smaller than n_clusters (34). Possibly due to duplicate points in X.
  kmeans = KMeans(n_clusters=len(filter_go_stations),random_state=0, init='k-means++').fit(partial_times.to_numpy())

KeyboardInterrupt: ignored

In [ ]:
#Kmean Algorithms
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
#df= np.array([[1,3],[3,3],[4,3],[5,3],[1,2],[4,2],[1,1],[2,1]])
buses_numpy = buses.to_numpy()
buses_numpy[0]

print('buses_numpy: \n',buses_numpy)
kmeans = KMeans(n_clusters=24).fit(buses_numpy)

print(kmeans.labels_)

for i in range(len(buses_numpy)):
    print(buses_numpy[i][0],buses_numpy[i][1],kmeans.labels_[i])

colors = np.array(['r','b','g','y','k','c','m','tomato','cyan','teal'])


#plt.scatter(X[:,0],X[:,1] , color = colors[kmeans.labels_])

buses_numpy:
 [[    1 22557]
 [    2 23138]
 [    3 23212]
 [    4 23215]
 [    5 23260]
 [    6 23289]
 [    7 23303]
 [    8 23491]
 [    9 23608]
 [   10 23611]
 [   11 23714]
 [   12 23791]
 [   13 23793]
 [   14 24120]
 [   15 24296]
 [   16 24298]
 [   17 24669]
 [   18 24862]
 [   19 25010]
 [   20 25187]
 [   21 26255]
 [   22 26672]
 [   23 26856]
 [   24 27163]
 [   25 27260]
 [   26 27314]
 [   27 27364]
 [   28 27367]
 [   29 27437]
 [   30 27441]
 [   31 27524]
 [   32 27583]
 [   33 27658]
 [   34 27661]
 [   35 27759]
 [   36 27804]
 [   37 27805]
 [   38 27810]
 [   39 27964]
 [   40 28216]
 [   41 28302]
 [   42 28304]
 [   43 28305]
 [   44 28310]
 [   45 28312]
 [   46 28313]
 [   47 28315]
 [   48 28319]
 [   49 28319]
 [   50 28411]
 [   51 28413]
 [   52 28474]
 [   53 28541]
 [   54 28609]
 [   55 28613]
 [   56 28662]
 [   57 28759]
 [   58 28823]
 [   59 28827]
 [   60 29074]
 [   61 29406]
 [   62 29493]
 [   63 29509]
 [   64 30893]
 [   65 30937]
 [   66 31014]
 [   67 31079]
 [   68 31115]
 [   69 31130]
 [   70 31150]
 [   71 31174]
 [   72 31237]
 [   73 31307]
 [   74 31446]
 [   75 31514]
 [   76 31586]
 [   77 31590]
 [   78 31600]
 [   79 31601]
 [   80 31605]
 [   81 31606]
 [   82 31738]
 [   83 31888]
 [   84 31892]
 [   85 32021]
 [   86 32093]
 [   87 32098]
 [   88 32100]
 [   89 32103]
 [   90 32117]
 [   91 32155]
 [   92 32239]
 [   93 32326]
 [   94 32474]
 [   95 32626]
 [   96 32629]
 [   97 32637]
 [   98 32654]
 [   99 32661]
 [  100 32672]
 [  101 32692]
 [  102 32894]
 [  103 33045]
 [  104 33485]
 [  105 33491]
 [  106 33570]
 [  107 33572]
 [  108 34124]
 [  109 34225]
 [  110 34375]
 [  111 34379]
 [  112 34442]
 [  113 34555]
 [  114 36281]
 [  115 36464]
 [  116 36470]
 [  117 36474]
 [  118 36745]
 [  119 36945]
 [  120 36946]
 [  121 37037]
 [  122 37087]
 [  123 37087]
 [  124 37220]
 [  125 37222]
 [  126 37300]
 [  127 37449]
 [  128 37451]
 [  129 37567]
 [  130 37570]
 [  131 37723]
 [  132 37784]
 [  133 37976]
 [  134 37980]
 [  135 37993]
 [  136 38349]
 [  137 38351]
 [  138 38460]
 [  139 38463]
 [  140 38599]
 [  141 38683]
 [  142 38878]
 [  143 38998]
 [  144 39000]
 [  145 39003]
 [  146 39004]
 [  147 39006]
 [  148 39008]
 [  149 39181]
 [  150 39434]
 [  151 39440]
 [  152 39456]
 [  153 39543]
 [  154 39550]
 [  155 39678]
 [  156 39725]
 [  157 39740]
 [  158 41102]
 [  159 41108]
 [  160 41110]
 [  161 41155]
 [  162 41168]
 [  163 41203]
 [  164 41250]
 [  165 41253]
 [  166 41254]
 [  167 41257]
 [  168 41415]
 [  169 41752]
 [  170 41756]
 [  171 41757]
 [  172 41761]
 [  173 41765]
 [  174 41769]
 [  175 41775]
 [  176 41780]
 [  177 41783]
 [  178 41786]
 [  179 41787]
 [  180 41789]
 [  181 42059]
 [  182 42060]
 [  183 42063]
 [  184 42066]
 [  185 42067]
 [  186 42068]
 [  187 42070]
 [  188 42143]
 [  189 42145]
 [  190 42236]
 [  191 42503]
 [  192 42776]
 [  193 42779]
 [  194 42843]
 [  195 43063]
 [  196 43076]
 [  197 43163]
 [  198 43275]
 [  199 43277]
 [  200 43338]
 [  201 43340]
 [  202 43505]
 [  203 43510]
 [  204 43662]
 [  205 43743]
 [  206 43749]
 [  207 43829]
 [  208 43833]
 [  209 44466]
 [  210 44607]
 [  211 44608]
 [  212 44613]
 [  213 46315]
 [  214 46340]
 [  215 46419]
 [  216 46459]
 [  217 46465]
 [  218 46521]
 [  219 46642]
 [  220 46668]
 [  221 46691]
 [  222 46693]
 [  223 46759]
 [  224 46767]
 [  225 46769]
 [  226 46777]
 [  227 46781]
 [  228 47249]
 [  229 47345]
 [  230 47463]
 [  231 47472]
 [  232 47527]
 [  233 47542]
 [  234 47655]
 [  235 47791]
 [  236 47792]
 [  237 47794]
 [  238 47808]
 [  239 47921]
 [  240 47924]
 [  241 48000]
 [  242 48001]
 [  243 48181]
 [  244 48267]
 [  245 48535]
 [  246 48538]
 [  247 48538]
 [  248 48539]
 [  249 48540]
 [  250 48542]
 [  251 48542]
 [  252 48543]
 [  253 48545]
 [  254 48547]
 [  255 48553]
 [  256 48554]
 [  257 48773]
 [  258 48790]
 [  259 48852]
 [  260 48885]
 [  261 49003]
 [  262 49093]
 [  263 49101]
 [  264 49104]
 [  265 49205]
 [  266 49268]
 [  267 49284]
 [  268 49393]
 [  269 49404]
 [  270 49720]
 [  271 51184]
 [  272 51185]
 [  273 51396]
 [  274 51777]
 [  275 52017]
 [  276 52082]
 [  277 52083]
 [  278 52089]
 [  279 52093]
 [  280 52095]
 [  281 52096]
 [  282 52102]
 [  283 52112]
 [  284 52162]
 [  285 52362]
 [  286 52363]
 [  287 52367]
 [  288 52436]
 [  289 52547]
 [  290 52549]
 [  291 52711]
 [  292 53186]
 [  293 53394]
 [  294 53396]
 [  295 53399]
 [  296 53528]
 [  297 53538]
 [  298 53663]
 [  299 53727]
 [  300 53889]
 [  301 53965]
 [  302 54057]
 [  303 54066]
 [  304 54075]
 [  305 54133]
 [  306 54232]
 [  307 54282]
 [  308 54445]
 [  309 54649]
 [  310 54757]
 [  311 54882]
 [  312 55222]
 [  313 55254]
 [  314 55571]
 [  315 55600]
 [  316 55670]
 [  317 55805]
 [  318 55890]
 [  319 55953]
 [  320 56107]
 [  321 56256]
 [  322 56257]
 [  323 56391]
 [  324 56436]
 [  325 56470]
 [  326 56473]
 [  327 56484]
 [  328 56506]
 [  329 56511]
 [  330 56563]
 [  331 56631]
 [  332 56632]
 [  333 56634]
 [  334 56635]
 [  335 56637]
 [  336 56638]
 [  337 56696]
 [  338 56756]
 [  339 56811]
 [  340 56963]
 [  341 56965]
 [  342 56968]
 [  343 56969]
 [  344 56971]
 [  345 57071]
 [  346 57278]
 [  347 57281]
 [  348 57460]
 [  349 57522]
 [  350 57524]
 [  351 59209]
 [  352 59804]
 [  353 59822]
 [  354 59950]
 [  355 60372]
 [  356 60374]
 [  357 60377]
 [  358 60378]
 [  359 60381]
 [  360 60388]
 [  361 60438]
 [  362 60440]
 [  363 60625]
 [  364 60626]
 [  365 60685]
 [  366 60817]
 [  367 60818]
 [  368 60837]
 [  369 60947]
 [  370 61032]
 [  371 61035]
 [  372 61036]
 [  373 61044]
 [  374 61045]
 [  375 61385]
 [  376 61387]
 [  377 61389]
 [  378 61390]
 [  379 61391]
 [  380 61394]
 [  381 61395]
 [  382 61397]
 [  383 61397]
 [  384 61398]
 [  385 61399]
 [  386 61400]
 [  387 61403]
 [  388 61472]
 [  389 61474]
 [  390 61532]
 [  391 61535]
 [  392 61551]
 [  393 61604]
 [  394 61678]
 [  395 61929]
 [  396 61934]
 [  397 62313]
 [  398 62565]
 [  399 62581]
 [  400 62655]
 [  401 62731]
 [  402 62840]
 [  403 62843]
 [  404 62846]
 [  405 62850]
 [  406 62851]
 [  407 63114]
 [  408 63116]
 [  409 63123]
 [  410 63160]
 [  411 63913]
 [  412 63930]
 [  413 64065]
 [  414 64145]
 [  415 64233]
 [  416 64269]
 [  417 64812]
 [  418 64960]
 [  419 65018]
 [  420 65098]
 [  421 65131]
 [  422 65133]
 [  423 65137]
 [  424 65276]
 [  425 65276]
 [  426 65277]
 [  427 65303]
 [  428 65482]
 [  429 65896]
 [  430 65898]
 [  431 65994]
 [  432 66087]
 [  433 66087]
 [  434 66089]
 [  435 66093]
 [  436 66095]
 [  437 66098]
 [  438 66100]
 [  439 66107]
 [  440 66128]
 [  441 66141]
 [  442 66200]
 [  443 66367]
 [  444 66368]
 [  445 66450]
 [  446 66568]
 [  447 66572]
 [  448 66573]
 [  449 66578]
 [  450 66662]
 [  451 66853]
 [  452 67219]
 [  453 67220]
 [  454 70251]
 [  455 70253]
 [  456 70255]
 [  457 70321]
 [  458 70322]
 [  459 70323]
 [  460 70325]
 [  461 70328]
 [  462 70331]
 [  463 70334]
 [  464 70336]
 [  465 70339]
 [  466 70342]
 [  467 70346]
 [  468 70581]
 [  469 70678]
 [  470 70680]
 [  471 70691]
 [  472 70755]
 [  473 70857]
 [  474 70992]
 [  475 71495]
 [  476 71499]
 [  477 71646]
 [  478 71913]
 [  479 71914]
 [  480 72175]
 [  481 76369]
 [  482 76884]
 [  483 77053]
 [  484 77355]
 [  485 78081]
 [  486 78824]
 [  487 78834]
 [  488 79405]
 [  489 79876]]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 22 22 22 22 22 22 22 22 22
 22 22 22 22 22 22 22 22 22 22  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1 21 21 21 21 21 21 21 21 21 21 11 11 11 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 16 16 16 16 16 16 16 16 16
 16 16 16 16 16 16 16 16 16 16 16 16 16  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 19 19 19 19
 19 19 19 19 19 19 19 19 19 19 19  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 13 13 13 13 13 13  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17
 17  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23
 23 23 23 23 23 23 23 23 23 23 23 23 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14  7  7  7  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
 18 18 18 18 18  9  9  9  9]
1 22557 10
2 23138 10
3 23212 10
4 23215 10
5 23260 10
6 23289 10
7 23303 10
8 23491 10
9 23608 10
10 23611 10
11 23714 10
12 23791 10
13 23793 10
14 24120 10
15 24296 10
16 24298 10
17 24669 10
18 24862 10
19 25010 10
20 25187 10
21 26255 15
22 26672 15
23 26856 15
24 27163 15
25 27260 15
26 27314 15
27 27364 15
28 27367 15
29 27437 15
30 27441 15
31 27524 15
32 27583 15
33 27658 15
34 27661 15
35 27759 15
36 27804 15
37 27805 15
38 27810 15
39 27964 15
40 28216 5
41 28302 5
42 28304 5
43 28305 5
44 28310 5
45 28312 5
46 28313 5
47 28315 5
48 28319 5
49 28319 5
50 28411 5
51 28413 5
52 28474 5
53 28541 5
54 28609 5
55 28613 5
56 28662 5
57 28759 5
58 28823 5
59 28827 5
60 29074 5
61 29406 5
62 29493 5
63 29509 5
64 30893 22
65 30937 22
66 31014 22
67 31079 22
68 31115 22
69 31130 22
70 31150 22
71 31174 22
72 31237 22
73 31307 22
74 31446 22
75 31514 22
76 31586 22
77 31590 22
78 31600 22
79 31601 22
80 31605 22
81 31606 22
82 31738 22
83 31888 1
84 31892 1
85 32021 1
86 32093 1
87 32098 1
88 32100 1
89 32103 1
90 32117 1
91 32155 1
92 32239 1
93 32326 1
94 32474 1
95 32626 1
96 32629 1
97 32637 1
98 32654 1
99 32661 1
100 32672 1
101 32692 1
102 32894 1
103 33045 1
104 33485 21
105 33491 21
106 33570 21
107 33572 21
108 34124 21
109 34225 21
110 34375 21
111 34379 21
112 34442 21
113 34555 21
114 36281 11
115 36464 11
116 36470 11
117 36474 11
118 36745 11
119 36945 11
120 36946 11
121 37037 11
122 37087 11
123 37087 11
124 37220 11
125 37222 11
126 37300 11
127 37449 11
128 37451 11
129 37567 11
130 37570 11
131 37723 11
132 37784 11
133 37976 11
134 37980 11
135 37993 11
136 38349 16
137 38351 16
138 38460 16
139 38463 16
140 38599 16
141 38683 16
142 38878 16
143 38998 16
144 39000 16
145 39003 16
146 39004 16
147 39006 16
148 39008 16
149 39181 16
150 39434 16
151 39440 16
152 39456 16
153 39543 16
154 39550 16
155 39678 16
156 39725 16
157 39740 16
158 41102 2
159 41108 2
160 41110 2
161 41155 2
162 41168 2
163 41203 2
164 41250 2
165 41253 2
166 41254 2
167 41257 2
168 41415 2
169 41752 2
170 41756 2
171 41757 2
172 41761 2
173 41765 2
174 41769 2
175 41775 2
176 41780 2
177 41783 2
178 41786 2
179 41787 2
180 41789 2
181 42059 2
182 42060 2
183 42063 2
184 42066 2
185 42067 2
186 42068 2
187 42070 2
188 42143 2
189 42145 2
190 42236 2
191 42503 2
192 42776 12
193 42779 12
194 42843 12
195 43063 12
196 43076 12
197 43163 12
198 43275 12
199 43277 12
200 43338 12
201 43340 12
202 43505 12
203 43510 12
204 43662 12
205 43743 12
206 43749 12
207 43829 12
208 43833 12
209 44466 12
210 44607 12
211 44608 12
212 44613 12
213 46315 19
214 46340 19
215 46419 19
216 46459 19
217 46465 19
218 46521 19
219 46642 19
220 46668 19
221 46691 19
222 46693 19
223 46759 19
224 46767 19
225 46769 19
226 46777 19
227 46781 19
228 47249 6
229 47345 6
230 47463 6
231 47472 6
232 47527 6
233 47542 6
234 47655 6
235 47791 6
236 47792 6
237 47794 6
238 47808 6
239 47921 6
240 47924 6
241 48000 6
242 48001 6
243 48181 6
244 48267 6
245 48535 13
246 48538 13
247 48538 13
248 48539 13
249 48540 13
250 48542 13
251 48542 13
252 48543 13
253 48545 13
254 48547 13
255 48553 13
256 48554 13
257 48773 13
258 48790 13
259 48852 13
260 48885 13
261 49003 13
262 49093 13
263 49101 13
264 49104 13
265 49205 13
266 49268 13
267 49284 13
268 49393 13
269 49404 13
270 49720 13
271 51184 4
272 51185 4
273 51396 4
274 51777 4
275 52017 4
276 52082 4
277 52083 4
278 52089 4
279 52093 4
280 52095 4
281 52096 4
282 52102 4
283 52112 4
284 52162 4
285 52362 4
286 52363 4
287 52367 4
288 52436 4
289 52547 4
290 52549 4
291 52711 4
292 53186 17
293 53394 17
294 53396 17
295 53399 17
296 53528 17
297 53538 17
298 53663 17
299 53727 17
300 53889 17
301 53965 17
302 54057 17
303 54066 17
304 54075 17
305 54133 17
306 54232 17
307 54282 17
308 54445 17
309 54649 17
310 54757 17
311 54882 17
312 55222 17
313 55254 17
314 55571 8
315 55600 8
316 55670 8
317 55805 8
318 55890 8
319 55953 8
320 56107 8
321 56256 8
322 56257 8
323 56391 8
324 56436 8
325 56470 8
326 56473 8
327 56484 8
328 56506 8
329 56511 8
330 56563 8
331 56631 8
332 56632 8
333 56634 8
334 56635 8
335 56637 8
336 56638 8
337 56696 8
338 56756 8
339 56811 8
340 56963 8
341 56965 8
342 56968 8
343 56969 8
344 56971 8
345 57071 8
346 57278 8
347 57281 8
348 57460 8
349 57522 8
350 57524 8
351 59209 0
352 59804 0
353 59822 0
354 59950 0
355 60372 0
356 60374 0
357 60377 0
358 60378 0
359 60381 0
360 60388 0
361 60438 0
362 60440 0
363 60625 0
364 60626 0
365 60685 0
366 60817 0
367 60818 0
368 60837 0
369 60947 23
370 61032 23
371 61035 23
372 61036 23
373 61044 23
374 61045 23
375 61385 23
376 61387 23
377 61389 23
378 61390 23
379 61391 23
380 61394 23
381 61395 23
382 61397 23
383 61397 23
384 61398 23
385 61399 23
386 61400 23
387 61403 23
388 61472 23
389 61474 23
390 61532 23
391 61535 23
392 61551 23
393 61604 23
394 61678 23
395 61929 23
396 61934 23
397 62313 20
398 62565 20
399 62581 20
400 62655 20
401 62731 20
402 62840 20
403 62843 20
404 62846 20
405 62850 20
406 62851 20
407 63114 20
408 63116 20
409 63123 20
410 63160 20
411 63913 14
412 63930 14
413 64065 14
414 64145 14
415 64233 14
416 64269 14
417 64812 14
418 64960 14
419 65018 14
420 65098 14
421 65131 14
422 65133 14
423 65137 14
424 65276 14
425 65276 14
426 65277 14
427 65303 14
428 65482 14
429 65896 7
430 65898 7

431 65994 7
432 66087 7
433 66087 7
434 66089 7
435 66093 7
436 66095 7
437 66098 7
438 66100 7
439 66107 7
440 66128 7
441 66141 7
442 66200 7
443 66367 7
444 66368 7
445 66450 7
446 66568 7
447 66572 7
448 66573 7
449 66578 7
450 66662 7
451 66853 7
452 67219 7
453 67220 7
454 70251 3
455 70253 3
456 70255 3
457 70321 3
458 70322 3
459 70323 3
460 70325 3
461 70328 3
462 70331 3
463 70334 3
464 70336 3
465 70339 3
466 70342 3
467 70346 3
468 70581 3
469 70678 3
470 70680 3
471 70691 3
472 70755 3
473 70857 3
474 70992 3
475 71495 3
476 71499 3
477 71646 3
478 71913 3
479 71914 3
480 72175 3
481 76369 18
482 76884 18
483 77053 18
484 77355 18
485 78081 18
486 78824 9
487 78834 9
488 79405 9
489 79876 9